/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

int npc_vigilance_raw(int, int, int, int, int);
int npc_effective_vigilance(int, int, int, int, int);
int zombie_alertness_raw(int, int, int);
int zombie_alertness_formula(int, int, int);

int npc_vigilance_raw(int base __attribute__((unused)), int startled __attribute__((unused)), int tired __attribute__((unused)), int fatigue_pct __attribute__((unused)), int energy_deficit_pct __attribute__((unused))) {
    return ((base + ((startled == 1) ? 25 : 0)) - (((tired == 1) ? 15 : 0) + (((fatigue_pct * 20) / 100) + ((energy_deficit_pct * 15) / 100))));
}

int npc_effective_vigilance(int base __attribute__((unused)), int startled __attribute__((unused)), int tired __attribute__((unused)), int fatigue_pct __attribute__((unused)), int energy_deficit_pct __attribute__((unused))) {
    if ((npc_vigilance_raw(base, startled, tired, fatigue_pct, energy_deficit_pct) < 0)) {
    return 0;
    } else {
    if ((npc_vigilance_raw(base, startled, tired, fatigue_pct, energy_deficit_pct) > 100)) {
    return 100;
    } else {
    return npc_vigilance_raw(base, startled, tired, fatigue_pct, energy_deficit_pct);
    }
    }
}

int zombie_alertness_raw(int mood __attribute__((unused)), int hunger_pct __attribute__((unused)), int aggression_pct __attribute__((unused))) {
    return (((mood == 0) ? 10 : ((mood == 1) ? 40 : ((mood == 2) ? 70 : 95))) + (((hunger_pct * 10) / 100) + ((aggression_pct * 10) / 100)));
}

int zombie_alertness_formula(int mood __attribute__((unused)), int hunger_pct __attribute__((unused)), int aggression_pct __attribute__((unused))) {
    if ((zombie_alertness_raw(mood, hunger_pct, aggression_pct) < 0)) {
    return 0;
    } else {
    if ((zombie_alertness_raw(mood, hunger_pct, aggression_pct) > 100)) {
    return 100;
    } else {
    return zombie_alertness_raw(mood, hunger_pct, aggression_pct);
    }
    }
}

