/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

int ambient_level_max();
int ambient_level_default();
int ambient_clamp(int);
int ambient_step(int, int);
int ambient_boost_permille(int);

int ambient_level_max(void) {
    return 10;
}

int ambient_level_default(void) {
    return 3;
}

int ambient_clamp(int level __attribute__((unused))) {
    if ((level < 0)) {
    return 0;
    } else {
    if ((level > 10)) {
    return 10;
    } else {
    return level;
    }
    }
}

int ambient_step(int level __attribute__((unused)), int dir __attribute__((unused))) {
    return ambient_clamp((level + dir));
}

int ambient_boost_permille(int level __attribute__((unused))) {
    return (ambient_clamp(level) * 40);
}

