/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

int material_resist_pct(int);
int on_paper_fragment_damage(int, int, int);
int on_paper_fragment_state_for_hp(int, int);
int on_papercraft_interact_damage_falloff(int, int);
int on_brick_weapon_damage(int, int);
int on_brick_debris_count(int, int);
int on_brick_paper_material(int);
int on_brick_cell_max_hp(int);

int material_resist_pct(int material __attribute__((unused))) {
    if ((material == 0)) {
    return 0;
    } else {
    if ((material == 1)) {
    return 20;
    } else {
    if ((material == 2)) {
    return 50;
    } else {
    return 75;
    }
    }
    }
}

int on_paper_fragment_damage(int material __attribute__((unused)), int hp __attribute__((unused)), int damage __attribute__((unused))) {
    int effective_damage __attribute__((unused)) = (damage - ((damage * material_resist_pct(material)) / 100));
    if ((effective_damage >= hp)) {
    return 0;
    } else {
    return (hp - effective_damage);
    }
}

int on_paper_fragment_state_for_hp(int hp __attribute__((unused)), int max_hp __attribute__((unused))) {
    if ((hp <= 0)) {
    return 3;
    } else {
    if (((hp * 100) < (max_hp * 25))) {
    return 2;
    } else {
    if (((hp * 100) < (max_hp * 60))) {
    return 1;
    } else {
    return 0;
    }
    }
    }
}

int on_papercraft_interact_damage_falloff(int base_damage __attribute__((unused)), int dist_permille __attribute__((unused))) {
    int clamped __attribute__((unused)) = ((dist_permille > 1000) ? 1000 : ((dist_permille < 0) ? 0 : dist_permille));
    return ((base_damage * (1000 - clamped)) / 1000);
}

int on_brick_weapon_damage(int weapon __attribute__((unused)), int base_damage __attribute__((unused))) {
    if ((weapon == 6)) {
    return (base_damage * 5);
    } else {
    if ((weapon == 4)) {
    return (base_damage + (base_damage / 4));
    } else {
    if ((weapon == 0)) {
    return 0;
    } else {
    if ((weapon == 5)) {
    return 0;
    } else {
    if ((weapon == 7)) {
    return 0;
    } else {
    return base_damage;
    }
    }
    }
    }
    }
}

int on_brick_debris_count(int prev_state __attribute__((unused)), int new_state __attribute__((unused))) {
    if ((new_state <= prev_state)) {
    return 0;
    } else {
    if ((new_state == 3)) {
    return 4;
    } else {
    if ((new_state == 2)) {
    return 2;
    } else {
    if ((new_state == 1)) {
    return 1;
    } else {
    return 0;
    }
    }
    }
    }
}

int on_brick_paper_material(int brick_kind __attribute__((unused))) {
    if ((brick_kind == 0)) {
    return 2;
    } else {
    return 2;
    }
}

int on_brick_cell_max_hp(int brick_kind __attribute__((unused))) {
    if ((brick_kind == 0)) {
    return 80;
    } else {
    return 80;
    }
}

