/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

int buggy_top_speed_milli();
int buggy_reverse_top_speed_milli();
int lerp_permille(int, int, int, int, int);
int buggy_drive_force_permille(int);
int buggy_turn_rate_milli(int);
int buggy_steer_authority_permille(int);
int buggy_lateral_grip_permille(int);

int buggy_top_speed_milli(void) {
    return 6240;
}

int buggy_reverse_top_speed_milli(void) {
    return 1800;
}

int lerp_permille(int a __attribute__((unused)), int b __attribute__((unused)), int x __attribute__((unused)), int lo __attribute__((unused)), int hi __attribute__((unused))) {
    return (a + (((b - a) * (x - lo)) / (hi - lo)));
}

int buggy_drive_force_permille(int speed __attribute__((unused))) {
    if ((speed < 0)) {
    return 1300;
    } else {
    if ((speed < 220)) {
    return lerp_permille(1300, 920, speed, 0, 220);
    } else {
    if ((speed < 520)) {
    return lerp_permille(920, 620, speed, 220, 520);
    } else {
    if ((speed < 780)) {
    return lerp_permille(620, 840, speed, 520, 780);
    } else {
    if ((speed < 1000)) {
    return (840 - ((780 * (((((((speed - 780) * 1000) / 220) * (((speed - 780) * 1000) / 220)) / 1000) * (3000 - (2 * (((speed - 780) * 1000) / 220)))) / 1000)) / 1000));
    } else {
    return 60;
    }
    }
    }
    }
    }
}

int buggy_turn_rate_milli(int abs_norm __attribute__((unused))) {
    return lerp_permille(3100, 900, ((abs_norm > 1000) ? 1000 : ((abs_norm < 0) ? 0 : abs_norm)), 0, 1000);
}

int buggy_steer_authority_permille(int abs_norm __attribute__((unused))) {
    return lerp_permille(380, 1000, ((abs_norm > 1000) ? 1000 : ((abs_norm < 0) ? 0 : abs_norm)), 0, 1000);
}

int buggy_lateral_grip_permille(int abs_norm __attribute__((unused))) {
    return ((120 * lerp_permille(620, 1300, ((abs_norm > 1000) ? 1000 : ((abs_norm < 0) ? 0 : abs_norm)), 0, 1000)) / 1000);
}

