/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

int chest_max_hp(int);
int chest_tier_for_roll(int);
int chest_loot_weapon(int, int);
int chest_damage_permille(int);

int chest_max_hp(int tier __attribute__((unused))) {
    if ((tier <= 0)) {
    return 100;
    } else {
    if ((tier == 1)) {
    return 240;
    } else {
    return 420;
    }
    }
}

int chest_tier_for_roll(int roll __attribute__((unused))) {
    if ((roll < 70)) {
    return 0;
    } else {
    if ((roll < 93)) {
    return 1;
    } else {
    return 2;
    }
    }
}

int chest_loot_weapon(int tier __attribute__((unused)), int roll __attribute__((unused))) {
    if ((tier <= 0)) {
    if ((roll < 40)) {
    return 1;
    } else {
    if ((roll < 75)) {
    return 2;
    } else {
    return 3;
    }
    }
    } else {
    if ((tier == 1)) {
    if ((roll < 30)) {
    return 3;
    } else {
    if ((roll < 55)) {
    return 5;
    } else {
    if ((roll < 80)) {
    return 4;
    } else {
    return 2;
    }
    }
    }
    } else {
    if ((roll < 40)) {
    return 4;
    } else {
    if ((roll < 80)) {
    return 6;
    } else {
    return 5;
    }
    }
    }
    }
}

int chest_damage_permille(int weapon __attribute__((unused))) {
    if ((weapon == 5)) {
    return 1500;
    } else {
    if ((weapon == 6)) {
    return 2000;
    } else {
    if ((weapon == 0)) {
    return 1200;
    } else {
    return 1000;
    }
    }
    }
}

