/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

int cutscene_effect_noop();
int cutscene_effect_advance_stage();
int cutscene_effect_trigger_awareness();
int cutscene_effect_grant_contact();
int cutscene_effect_post_message();
int on_tyler_cutscene_effect_is_mechanical(int);
int on_tyler_cutscene_trust_threshold_met(int, int);
int on_tyler_cutscene_urgency_window_met(int, int);
int on_tyler_cutscene_trigger_ready(int, int, int, int);

int cutscene_effect_noop(void) {
    return 0;
}

int cutscene_effect_advance_stage(void) {
    return 1;
}

int cutscene_effect_trigger_awareness(void) {
    return 2;
}

int cutscene_effect_grant_contact(void) {
    return 3;
}

int cutscene_effect_post_message(void) {
    return 4;
}

int on_tyler_cutscene_effect_is_mechanical(int effect_code __attribute__((unused))) {
    return (effect_code > cutscene_effect_noop());
}

int on_tyler_cutscene_trust_threshold_met(int player_trust __attribute__((unused)), int required_trust __attribute__((unused))) {
    return (player_trust >= required_trust);
}

int on_tyler_cutscene_urgency_window_met(int event_live_elapsed __attribute__((unused)), int urgency_threshold __attribute__((unused))) {
    return (event_live_elapsed >= urgency_threshold);
}

int on_tyler_cutscene_trigger_ready(int player_trust __attribute__((unused)), int required_trust __attribute__((unused)), int one_shot __attribute__((unused)), int already_seen __attribute__((unused))) {
    if (((one_shot == 1) && (already_seen == 1))) {
    return 0;
    } else {
    return on_tyler_cutscene_trust_threshold_met(player_trust, required_trust);
    }
}

