/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

int bug_hidden_0(int, int, int, int, int, int, int, int);
int bug_hidden_1(int, int, int, int, int, int, int, int);
int bug_hidden_2(int, int, int, int, int, int, int, int);
int bug_hidden_3(int, int, int, int, int, int, int, int);
int bug_hidden_4(int, int, int, int, int, int, int, int);
int bug_hidden_5(int, int, int, int, int, int, int, int);
int bug_hidden_6(int, int, int, int, int, int, int, int);
int bug_hidden_7(int, int, int, int, int, int, int, int);
int bug_attack_raw(int, int, int, int, int, int, int, int);
int bug_attack_drive(int, int, int, int, int, int, int, int);
int bug_flee_raw(int, int, int, int, int, int, int, int);
int bug_flee_drive(int, int, int, int, int, int, int, int);
int bug_swarm_raw(int, int, int, int, int, int, int, int);
int bug_swarm_drive(int, int, int, int, int, int, int, int);

int bug_hidden_0(int hunger __attribute__((unused)), int swarm __attribute__((unused)), int heat __attribute__((unused)), int molt __attribute__((unused)), int vibe __attribute__((unused)), int pain __attribute__((unused)), int hive __attribute__((unused)), int light __attribute__((unused))) {
    return (((hunger * 5) + ((swarm * 5) + ((heat * 30) + ((molt * 5) + ((vibe * 10) + ((pain * 35) + ((hive * 20) + (light * -10)))))))) / 100);
}

int bug_hidden_1(int hunger __attribute__((unused)), int swarm __attribute__((unused)), int heat __attribute__((unused)), int molt __attribute__((unused)), int vibe __attribute__((unused)), int pain __attribute__((unused)), int hive __attribute__((unused)), int light __attribute__((unused))) {
    return (((hunger * -5) + ((swarm * -5) + ((heat * -10) + ((molt * 0) + ((vibe * 5) + ((pain * 25) + ((hive * -10) + (light * 45)))))))) / 100);
}

int bug_hidden_2(int hunger __attribute__((unused)), int swarm __attribute__((unused)), int heat __attribute__((unused)), int molt __attribute__((unused)), int vibe __attribute__((unused)), int pain __attribute__((unused)), int hive __attribute__((unused)), int light __attribute__((unused))) {
    return (((hunger * 5) + ((swarm * 40) + ((heat * 5) + ((molt * 5) + ((vibe * 5) + ((pain * -10) + ((hive * 35) + (light * -5)))))))) / 100);
}

int bug_hidden_3(int hunger __attribute__((unused)), int swarm __attribute__((unused)), int heat __attribute__((unused)), int molt __attribute__((unused)), int vibe __attribute__((unused)), int pain __attribute__((unused)), int hive __attribute__((unused)), int light __attribute__((unused))) {
    return (((hunger * 10) + ((swarm * 5) + ((heat * 5) + ((molt * 50) + ((vibe * 5) + ((pain * 10) + ((hive * 5) + (light * 10)))))))) / 100);
}

int bug_hidden_4(int hunger __attribute__((unused)), int swarm __attribute__((unused)), int heat __attribute__((unused)), int molt __attribute__((unused)), int vibe __attribute__((unused)), int pain __attribute__((unused)), int hive __attribute__((unused)), int light __attribute__((unused))) {
    return (((hunger * 5) + ((swarm * 10) + ((heat * 20) + ((molt * 0) + ((vibe * 45) + ((pain * 5) + ((hive * 10) + (light * 5)))))))) / 100);
}

int bug_hidden_5(int hunger __attribute__((unused)), int swarm __attribute__((unused)), int heat __attribute__((unused)), int molt __attribute__((unused)), int vibe __attribute__((unused)), int pain __attribute__((unused)), int hive __attribute__((unused)), int light __attribute__((unused))) {
    return (((hunger * 40) + ((swarm * 5) + ((heat * 15) + ((molt * 10) + ((vibe * 5) + ((pain * 5) + ((hive * 5) + (light * 5)))))))) / 100);
}

int bug_hidden_6(int hunger __attribute__((unused)), int swarm __attribute__((unused)), int heat __attribute__((unused)), int molt __attribute__((unused)), int vibe __attribute__((unused)), int pain __attribute__((unused)), int hive __attribute__((unused)), int light __attribute__((unused))) {
    return (((hunger * 5) + ((swarm * 5) + ((heat * 5) + ((molt * 5) + ((vibe * 5) + ((pain * 5) + ((hive * 60) + (light * 5)))))))) / 100);
}

int bug_hidden_7(int hunger __attribute__((unused)), int swarm __attribute__((unused)), int heat __attribute__((unused)), int molt __attribute__((unused)), int vibe __attribute__((unused)), int pain __attribute__((unused)), int hive __attribute__((unused)), int light __attribute__((unused))) {
    return (((hunger * 5) + ((swarm * -10) + ((heat * -5) + ((molt * 5) + ((vibe * 5) + ((pain * 5) + ((hive * -5) + (light * 55)))))))) / 100);
}

int bug_attack_raw(int h0 __attribute__((unused)), int h1 __attribute__((unused)), int h2 __attribute__((unused)), int h3 __attribute__((unused)), int h4 __attribute__((unused)), int h5 __attribute__((unused)), int h6 __attribute__((unused)), int h7 __attribute__((unused))) {
    return (((h0 * 40) + ((h5 * 30) + (h6 * 30))) / 100);
}

int bug_attack_drive(int h0 __attribute__((unused)), int h1 __attribute__((unused)), int h2 __attribute__((unused)), int h3 __attribute__((unused)), int h4 __attribute__((unused)), int h5 __attribute__((unused)), int h6 __attribute__((unused)), int h7 __attribute__((unused))) {
    if ((bug_attack_raw(h0, h1, h2, h3, h4, h5, h6, h7) < 0)) {
    return 0;
    } else {
    if ((bug_attack_raw(h0, h1, h2, h3, h4, h5, h6, h7) > 100)) {
    return 100;
    } else {
    return bug_attack_raw(h0, h1, h2, h3, h4, h5, h6, h7);
    }
    }
}

int bug_flee_raw(int h0 __attribute__((unused)), int h1 __attribute__((unused)), int h2 __attribute__((unused)), int h3 __attribute__((unused)), int h4 __attribute__((unused)), int h5 __attribute__((unused)), int h6 __attribute__((unused)), int h7 __attribute__((unused))) {
    return (((h1 * 60) + (h7 * 40)) / 100);
}

int bug_flee_drive(int h0 __attribute__((unused)), int h1 __attribute__((unused)), int h2 __attribute__((unused)), int h3 __attribute__((unused)), int h4 __attribute__((unused)), int h5 __attribute__((unused)), int h6 __attribute__((unused)), int h7 __attribute__((unused))) {
    if ((bug_flee_raw(h0, h1, h2, h3, h4, h5, h6, h7) < 0)) {
    return 0;
    } else {
    if ((bug_flee_raw(h0, h1, h2, h3, h4, h5, h6, h7) > 100)) {
    return 100;
    } else {
    return bug_flee_raw(h0, h1, h2, h3, h4, h5, h6, h7);
    }
    }
}

int bug_swarm_raw(int h0 __attribute__((unused)), int h1 __attribute__((unused)), int h2 __attribute__((unused)), int h3 __attribute__((unused)), int h4 __attribute__((unused)), int h5 __attribute__((unused)), int h6 __attribute__((unused)), int h7 __attribute__((unused))) {
    return (((h2 * 70) + (h4 * 30)) / 100);
}

int bug_swarm_drive(int h0 __attribute__((unused)), int h1 __attribute__((unused)), int h2 __attribute__((unused)), int h3 __attribute__((unused)), int h4 __attribute__((unused)), int h5 __attribute__((unused)), int h6 __attribute__((unused)), int h7 __attribute__((unused))) {
    if ((bug_swarm_raw(h0, h1, h2, h3, h4, h5, h6, h7) < 0)) {
    return 0;
    } else {
    if ((bug_swarm_raw(h0, h1, h2, h3, h4, h5, h6, h7) > 100)) {
    return 100;
    } else {
    return bug_swarm_raw(h0, h1, h2, h3, h4, h5, h6, h7);
    }
    }
}

