/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

int heli_hover_collective_permille();
int heli_collective_step_permille(int, int, int);
int heli_lift_permille(int);
int heli_cyclic_target_milli(int);
int heli_attitude_step_milli(int, int);
int heli_yaw_target_milli(int);
int heli_yaw_step_milli(int, int);
int heli_drag_permille(int);
int heli_vertical_damp_permille();
int heli_max_hspeed_milli();
int heli_max_vspeed_up_milli();
int heli_max_vspeed_down_milli();

int heli_hover_collective_permille(void) {
    return 500;
}

int heli_collective_step_permille(int cur __attribute__((unused)), int up __attribute__((unused)), int down __attribute__((unused))) {
    if ((up > 0)) {
    if (((cur + 9) > 1000)) {
    return 1000;
    } else {
    return (cur + 9);
    }
    } else {
    if ((down > 0)) {
    if (((cur - 9) < 0)) {
    return 0;
    } else {
    return (cur - 9);
    }
    } else {
    if ((cur > 500)) {
    if (((cur - 3) < 500)) {
    return 500;
    } else {
    return (cur - 3);
    }
    } else {
    if (((cur + 3) < 500)) {
    return (cur + 3);
    } else {
    return 500;
    }
    }
    }
    }
}

int heli_lift_permille(int collective __attribute__((unused))) {
    return (2 * collective);
}

int heli_cyclic_target_milli(int input_permille __attribute__((unused))) {
    return (input_permille * 24);
}

int heli_attitude_step_milli(int cur __attribute__((unused)), int target __attribute__((unused))) {
    return (cur + ((target - cur) / 10));
}

int heli_yaw_target_milli(int pedal_permille __attribute__((unused))) {
    return (pedal_permille * 2);
}

int heli_yaw_step_milli(int cur __attribute__((unused)), int target __attribute__((unused))) {
    return (cur + ((target - cur) / 7));
}

int heli_drag_permille(int speed_milli __attribute__((unused))) {
    return (3 + ((11 * speed_milli) / 2000));
}

int heli_vertical_damp_permille(void) {
    return 25;
}

int heli_max_hspeed_milli(void) {
    return 2400;
}

int heli_max_vspeed_up_milli(void) {
    return 550;
}

int heli_max_vspeed_down_milli(void) {
    return 700;
}

