/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

int labst_max_samples();
int labst_max_clones();
int labst_reach_tenths();
int labst_clamp(int, int, int);
int labst_kind_ok(int);
int labst_base_ok(int);
int labst_can_use(int, int, int, int);
int labst_sample_delta(int);
int labst_target_delta(int);
int labst_clone_delta(int);
int labst_refine_base(int);
int labst_heal(int);
int labst_opens_phone(int);

int labst_max_samples(void) {
    return 9;
}

int labst_max_clones(void) {
    return 8;
}

int labst_reach_tenths(void) {
    return 40;
}

int labst_clamp(int v __attribute__((unused)), int lo __attribute__((unused)), int hi __attribute__((unused))) {
    if ((v < lo)) {
    return lo;
    } else {
    if ((v > hi)) {
    return hi;
    } else {
    return v;
    }
    }
}

int labst_kind_ok(int k __attribute__((unused))) {
    return ((k >= 0) && (k <= 5));
}

int labst_base_ok(int b __attribute__((unused))) {
    return ((b >= 0) && (b <= 2));
}

int labst_can_use(int kind __attribute__((unused)), int base __attribute__((unused)), int samples __attribute__((unused)), int clones __attribute__((unused))) {
    return (labst_kind_ok(kind) && (labst_base_ok(base) && ((kind == 0) ? ((labst_clamp(samples, 0, 9) >= 1) && (labst_clamp(clones, 0, 8) < 8)) : ((kind == 1) ? (labst_clamp(samples, 0, 9) >= 2) : ((kind == 2) ? ((labst_clamp(samples, 0, 9) >= 1) && (labst_clamp(samples, 0, 9) < 9)) : ((kind == 3) ? (labst_clamp(clones, 0, 8) >= 1) : 1))))));
}

int labst_sample_delta(int kind __attribute__((unused))) {
    if ((kind == 0)) {
    return -1;
    } else {
    if ((kind == 1)) {
    return -2;
    } else {
    if ((kind == 2)) {
    return 1;
    } else {
    return 0;
    }
    }
    }
}

int labst_target_delta(int kind __attribute__((unused))) {
    if ((kind == 1)) {
    return 1;
    } else {
    return 0;
    }
}

int labst_clone_delta(int kind __attribute__((unused))) {
    if ((kind == 0)) {
    return 1;
    } else {
    if ((kind == 3)) {
    return -1;
    } else {
    return 0;
    }
    }
}

int labst_refine_base(int b __attribute__((unused))) {
    return ((labst_clamp(b, 0, 2) + 1) - (3 * ((labst_clamp(b, 0, 2) + 1) / 3)));
}

int labst_heal(int kind __attribute__((unused))) {
    if ((kind == 3)) {
    return 25;
    } else {
    return 0;
    }
}

int labst_opens_phone(int kind __attribute__((unused))) {
    return (kind == 5);
}

