/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

int ragdoll_body_mass_kg();
int ragdoll_default_pool_size();
int ragdoll_max_catchup_ticks();
int ragdoll_max_dt_ms();
int ragdoll_speed_cap_mmps();
int ragdoll_omega_cap_mradps();
int ragdoll_max_dv_mmps();
int ragdoll_max_carry_mmps();
int ragdoll_default_arm_drop_mrad();
int ragdoll_max_pelvis_offset_mm();
int ragdoll_max_spawn_lift_mm();
int ragdoll_contact_friction_pct();
int ragdoll_contact_omega_pct();
int ragdoll_max_push_mm();
int ragdoll_query_max();
int ragdoll_clamp(int, int, int);
int ragdoll_kind(int);
int ragdoll_damage(int);
int ragdoll_bone(int);
int ragdoll_abs(int);
int ragdoll_kind_from_weapon(int);
int ragdoll_standing_height_mm();
int ragdoll_lateral_unit_mm();
int ragdoll_height_permille(int);
int ragdoll_lateral_permille(int);
int ragdoll_side(int, int);
int ragdoll_default_bone(int);
int ragdoll_leg_bone(int, int);
int ragdoll_arm_bone(int, int);
int ragdoll_torso_bone(int);
int ragdoll_is_arm_hit(int, int);
int ragdoll_bone_from_hit(int, int, int, int);
int ragdoll_base_mmps(int, int);
int ragdoll_kind_cap_mmps(int);
int ragdoll_falloff_permille(int, int);
int ragdoll_impulse_raw(int, int, int);
int ragdoll_impulse_mmps(int, int, int);
int ragdoll_bone_gain_permille(int);
int ragdoll_blast_share_permille(int);
int ragdoll_spread_permille(int);
int ragdoll_segment_share_permille(int, int, int);
int ragdoll_dv_mmps(int, int, int);
int ragdoll_lift_pct(int);
int ragdoll_lift_mmps(int, int, int);
int ragdoll_spin_sign(int);
int ragdoll_spin_pct(int);
int ragdoll_spin_mradps(int, int, int);
int ragdoll_carry_permille(int);
int ragdoll_calm_tick(int, int, int);
int ragdoll_min_active_ticks(int);
int ragdoll_settle_ticks(int);
int ragdoll_max_active_ticks(int);
int ragdoll_should_freeze(int, int, int);
int ragdoll_frozen_hold_ticks(int);
int ragdoll_fade_ticks();
int ragdoll_hard_cap_ticks();
int ragdoll_should_despawn(int, int, int);
int ragdoll_fade_permille(int, int);
int ragdoll_kind_bonus(int);
int ragdoll_age_penalty(int);
int ragdoll_dist_penalty(int);
int ragdoll_fade_penalty(int);
int ragdoll_priority(int, int, int, int, int, int);
int ragdoll_evict_ok(int, int);

int ragdoll_body_mass_kg(void) {
    return 70;
}

int ragdoll_default_pool_size(void) {
    return 8;
}

int ragdoll_max_catchup_ticks(void) {
    return 6;
}

int ragdoll_max_dt_ms(void) {
    return 250;
}

int ragdoll_speed_cap_mmps(void) {
    return 40000;
}

int ragdoll_omega_cap_mradps(void) {
    return 90000;
}

int ragdoll_max_dv_mmps(void) {
    return 24000;
}

int ragdoll_max_carry_mmps(void) {
    return 30000;
}

int ragdoll_default_arm_drop_mrad(void) {
    return 1150;
}

int ragdoll_max_pelvis_offset_mm(void) {
    return 1500;
}

int ragdoll_max_spawn_lift_mm(void) {
    return 3000;
}

int ragdoll_contact_friction_pct(void) {
    return 85;
}

int ragdoll_contact_omega_pct(void) {
    return 90;
}

int ragdoll_max_push_mm(void) {
    return 500;
}

int ragdoll_query_max(void) {
    return 32;
}

int ragdoll_clamp(int v __attribute__((unused)), int lo __attribute__((unused)), int hi __attribute__((unused))) {
    if ((v < lo)) {
    return lo;
    } else {
    if ((v > hi)) {
    return hi;
    } else {
    return v;
    }
    }
}

int ragdoll_kind(int k __attribute__((unused))) {
    return ragdoll_clamp(k, 0, 3);
}

int ragdoll_damage(int d __attribute__((unused))) {
    return ragdoll_clamp(d, 0, 400);
}

int ragdoll_bone(int b __attribute__((unused))) {
    return ragdoll_clamp(b, 0, 16);
}

int ragdoll_abs(int v __attribute__((unused))) {
    if ((v < 0)) {
    return (0 - v);
    } else {
    return v;
    }
}

int ragdoll_kind_from_weapon(int weapon __attribute__((unused))) {
    if ((weapon == 6)) {
    return 1;
    } else {
    if (((weapon == 0) || ((weapon == 5) || (weapon == 7)))) {
    return 2;
    } else {
    if (((weapon >= 1) && (weapon <= 4))) {
    return 0;
    } else {
    return 3;
    }
    }
    }
}

int ragdoll_standing_height_mm(void) {
    return 1700;
}

int ragdoll_lateral_unit_mm(void) {
    return 300;
}

int ragdoll_height_permille(int dy_mm __attribute__((unused))) {
    if ((dy_mm < 0)) {
    return -1;
    } else {
    return ((ragdoll_clamp(dy_mm, 0, 1870) * 1000) / 1700);
    }
}

int ragdoll_lateral_permille(int dx_mm __attribute__((unused))) {
    return ((ragdoll_clamp(dx_mm, -300, 300) * 1000) / 300);
}

int ragdoll_side(int base __attribute__((unused)), int left __attribute__((unused))) {
    if ((left == 1)) {
    return base;
    } else {
    return (base + 1);
    }
}

int ragdoll_default_bone(int kind __attribute__((unused))) {
    if (((ragdoll_kind(kind) == 0) || (ragdoll_kind(kind) == 2))) {
    return 3;
    } else {
    return 0;
    }
}

int ragdoll_leg_bone(int h __attribute__((unused)), int left __attribute__((unused))) {
    return ragdoll_side(((h < 61) ? 15 : ((h < 313) ? 13 : 11)), left);
}

int ragdoll_arm_bone(int h __attribute__((unused)), int left __attribute__((unused))) {
    return ragdoll_side(((h < 557) ? 9 : ((h < 718) ? 7 : 5)), left);
}

int ragdoll_torso_bone(int h __attribute__((unused))) {
    if ((h < 618)) {
    return 0;
    } else {
    if ((h < 691)) {
    return 1;
    } else {
    if ((h < 774)) {
    return 2;
    } else {
    if ((h < 875)) {
    return 3;
    } else {
    return 4;
    }
    }
    }
    }
}

int ragdoll_is_arm_hit(int h __attribute__((unused)), int lat __attribute__((unused))) {
    return ((ragdoll_abs(ragdoll_clamp(lat, -1000, 1000)) >= 500) && ((h >= 438) && (h < 848)));
}

int ragdoll_bone_from_hit(int kind __attribute__((unused)), int hit_type __attribute__((unused)), int h __attribute__((unused)), int lat __attribute__((unused))) {
    if ((hit_type == 2)) {
    return 4;
    } else {
    if ((h < 0)) {
    return ragdoll_default_bone(kind);
    } else {
    if (ragdoll_is_arm_hit(ragdoll_clamp(h, 0, 1100), lat)) {
    return ragdoll_arm_bone(ragdoll_clamp(h, 0, 1100), ((lat >= 0) ? 1 : 0));
    } else {
    if ((ragdoll_clamp(h, 0, 1100) < 540)) {
    return ragdoll_leg_bone(ragdoll_clamp(h, 0, 1100), ((lat >= 0) ? 1 : 0));
    } else {
    return ragdoll_torso_bone(ragdoll_clamp(h, 0, 1100));
    }
    }
    }
    }
}

int ragdoll_base_mmps(int kind __attribute__((unused)), int dmg __attribute__((unused))) {
    if ((kind == 0)) {
    return (1200 + (dmg * 50));
    } else {
    if ((kind == 1)) {
    return (3500 + (dmg * 28));
    } else {
    if ((kind == 2)) {
    return (450 + (dmg * 10));
    } else {
    return 0;
    }
    }
    }
}

int ragdoll_kind_cap_mmps(int kind __attribute__((unused))) {
    if ((kind == 0)) {
    return 9000;
    } else {
    if ((kind == 1)) {
    return 18000;
    } else {
    if ((kind == 2)) {
    return 5000;
    } else {
    return 0;
    }
    }
    }
}

int ragdoll_falloff_permille(int kind __attribute__((unused)), int dist_pm __attribute__((unused))) {
    if ((ragdoll_kind(kind) == 1)) {
    return ragdoll_clamp((1000 - ((ragdoll_clamp(dist_pm, 0, 1000) * 700) / 1000)), 300, 1000);
    } else {
    return 1000;
    }
}

int ragdoll_impulse_raw(int kind __attribute__((unused)), int dmg __attribute__((unused)), int dist_pm __attribute__((unused))) {
    return ragdoll_clamp(((ragdoll_clamp(ragdoll_base_mmps(kind, dmg), 0, ragdoll_kind_cap_mmps(kind)) * ragdoll_falloff_permille(kind, dist_pm)) / 1000), 0, ragdoll_max_dv_mmps());
}

int ragdoll_impulse_mmps(int kind __attribute__((unused)), int damage __attribute__((unused)), int dist_pm __attribute__((unused))) {
    return ragdoll_impulse_raw(ragdoll_kind(kind), ragdoll_damage(damage), dist_pm);
}

int ragdoll_bone_gain_permille(int bone __attribute__((unused))) {
    if ((ragdoll_bone(bone) <= 3)) {
    return 1000;
    } else {
    if ((ragdoll_bone(bone) == 4)) {
    return 750;
    } else {
    if ((ragdoll_bone(bone) <= 6)) {
    return 900;
    } else {
    if ((ragdoll_bone(bone) <= 8)) {
    return 1100;
    } else {
    if ((ragdoll_bone(bone) <= 10)) {
    return 1300;
    } else {
    if ((ragdoll_bone(bone) <= 12)) {
    return 900;
    } else {
    if ((ragdoll_bone(bone) <= 14)) {
    return 1100;
    } else {
    return 1250;
    }
    }
    }
    }
    }
    }
    }
}

int ragdoll_blast_share_permille(int bone __attribute__((unused))) {
    if ((ragdoll_bone(bone) == 0)) {
    return 1100;
    } else {
    if ((ragdoll_bone(bone) == 1)) {
    return 1050;
    } else {
    if ((ragdoll_bone(bone) == 2)) {
    return 1000;
    } else {
    if ((ragdoll_bone(bone) == 3)) {
    return 950;
    } else {
    if ((ragdoll_bone(bone) == 4)) {
    return 800;
    } else {
    if ((ragdoll_bone(bone) <= 10)) {
    return 1000;
    } else {
    if ((ragdoll_bone(bone) <= 12)) {
    return 1200;
    } else {
    if ((ragdoll_bone(bone) <= 14)) {
    return 1250;
    } else {
    return 1300;
    }
    }
    }
    }
    }
    }
    }
    }
}

int ragdoll_spread_permille(int kind __attribute__((unused))) {
    if ((ragdoll_kind(kind) == 0)) {
    return 250;
    } else {
    if ((ragdoll_kind(kind) == 2)) {
    return 350;
    } else {
    return 0;
    }
    }
}

int ragdoll_segment_share_permille(int kind __attribute__((unused)), int hit_bone __attribute__((unused)), int seg_bone __attribute__((unused))) {
    if ((ragdoll_kind(kind) == 1)) {
    return ragdoll_blast_share_permille(ragdoll_bone(seg_bone));
    } else {
    if ((ragdoll_bone(seg_bone) == ragdoll_bone(hit_bone))) {
    return ragdoll_bone_gain_permille(ragdoll_bone(seg_bone));
    } else {
    return ragdoll_spread_permille(kind);
    }
    }
}

int ragdoll_dv_mmps(int mag __attribute__((unused)), int share __attribute__((unused)), int dir_pm __attribute__((unused))) {
    return ragdoll_clamp(((((ragdoll_clamp(mag, 0, 24000) * ragdoll_clamp(share, 0, 2000)) / 1000) * ragdoll_clamp(dir_pm, -1000, 1000)) / 1000), -24000, 24000);
}

int ragdoll_lift_pct(int kind __attribute__((unused))) {
    if ((kind == 1)) {
    return 55;
    } else {
    if ((kind == 0)) {
    return 6;
    } else {
    return 0;
    }
    }
}

int ragdoll_lift_mmps(int kind __attribute__((unused)), int mag __attribute__((unused)), int share __attribute__((unused))) {
    return ragdoll_clamp(((((ragdoll_clamp(mag, 0, 24000) * ragdoll_lift_pct(ragdoll_kind(kind))) / 100) * ragdoll_clamp(share, 0, 2000)) / 1000), 0, 24000);
}

int ragdoll_spin_sign(int bone __attribute__((unused))) {
    if ((bone == 0)) {
    return 0;
    } else {
    if ((bone >= 11)) {
    return -1;
    } else {
    return 1;
    }
    }
}

int ragdoll_spin_pct(int kind __attribute__((unused))) {
    if ((kind == 0)) {
    return 15;
    } else {
    if ((kind == 2)) {
    return 28;
    } else {
    return 0;
    }
    }
}

int ragdoll_spin_mradps(int kind __attribute__((unused)), int mag __attribute__((unused)), int bone __attribute__((unused))) {
    return (ragdoll_spin_sign(ragdoll_bone(bone)) * ((ragdoll_clamp(mag, 0, 24000) * ragdoll_spin_pct(ragdoll_kind(kind))) / 100));
}

int ragdoll_carry_permille(int kind __attribute__((unused))) {
    if ((ragdoll_kind(kind) == 1)) {
    return 700;
    } else {
    if ((ragdoll_kind(kind) == 3)) {
    return 1000;
    } else {
    return 900;
    }
    }
}

int ragdoll_calm_tick(int lin_mmps __attribute__((unused)), int ang_mradps __attribute__((unused)), int gap_mm __attribute__((unused))) {
    return ((lin_mmps <= 60) && ((ang_mradps <= 700) && (gap_mm <= 40)));
}

int ragdoll_min_active_ticks(int kind __attribute__((unused))) {
    if ((ragdoll_kind(kind) == 1)) {
    return 96;
    } else {
    if ((ragdoll_kind(kind) == 3)) {
    return 24;
    } else {
    return 40;
    }
    }
}

int ragdoll_settle_ticks(int kind __attribute__((unused))) {
    if ((ragdoll_kind(kind) == 1)) {
    return 40;
    } else {
    return 30;
    }
}

int ragdoll_max_active_ticks(int kind __attribute__((unused))) {
    if ((ragdoll_kind(kind) == 1)) {
    return 512;
    } else {
    if ((ragdoll_kind(kind) == 3)) {
    return 256;
    } else {
    return 384;
    }
    }
}

int ragdoll_should_freeze(int kind __attribute__((unused)), int age __attribute__((unused)), int calm_ticks __attribute__((unused))) {
    return ((age >= ragdoll_min_active_ticks(kind)) && ((calm_ticks >= ragdoll_settle_ticks(kind)) || (age >= ragdoll_max_active_ticks(kind))));
}

int ragdoll_frozen_hold_ticks(int kind __attribute__((unused))) {
    if ((ragdoll_kind(kind) == 1)) {
    return 448;
    } else {
    if ((ragdoll_kind(kind) == 3)) {
    return 320;
    } else {
    return 640;
    }
    }
}

int ragdoll_fade_ticks(void) {
    return 96;
}

int ragdoll_hard_cap_ticks(void) {
    return 1536;
}

int ragdoll_should_despawn(int kind __attribute__((unused)), int age __attribute__((unused)), int frozen_ticks __attribute__((unused))) {
    return ((age >= ragdoll_hard_cap_ticks()) || (frozen_ticks >= ragdoll_frozen_hold_ticks(kind)));
}

int ragdoll_fade_permille(int kind __attribute__((unused)), int frozen_ticks __attribute__((unused))) {
    if (((ragdoll_frozen_hold_ticks(kind) - ragdoll_clamp(frozen_ticks, 0, 100000)) <= 0)) {
    return 0;
    } else {
    if (((ragdoll_frozen_hold_ticks(kind) - ragdoll_clamp(frozen_ticks, 0, 100000)) >= ragdoll_fade_ticks())) {
    return 1000;
    } else {
    return (((ragdoll_frozen_hold_ticks(kind) - ragdoll_clamp(frozen_ticks, 0, 100000)) * 1000) / ragdoll_fade_ticks());
    }
    }
}

int ragdoll_kind_bonus(int kind __attribute__((unused))) {
    if ((kind == 1)) {
    return 400;
    } else {
    if ((kind == 2)) {
    return 150;
    } else {
    if ((kind == 0)) {
    return 100;
    } else {
    return 0;
    }
    }
    }
}

int ragdoll_age_penalty(int age __attribute__((unused))) {
    return ragdoll_clamp((ragdoll_clamp(age, 0, 100000) * 2), 0, 2500);
}

int ragdoll_dist_penalty(int dist_mm __attribute__((unused))) {
    return ragdoll_clamp((ragdoll_clamp(dist_mm, 0, 200000) / 8), 0, 2500);
}

int ragdoll_fade_penalty(int fade_pm __attribute__((unused))) {
    return (((1000 - ragdoll_clamp(fade_pm, 0, 1000)) * 3) / 2);
}

int ragdoll_priority(int state __attribute__((unused)), int age __attribute__((unused)), int dist_mm __attribute__((unused)), int kind __attribute__((unused)), int local __attribute__((unused)), int fade_pm __attribute__((unused))) {
    if ((state <= 0)) {
    return 0;
    } else {
    return ragdoll_clamp(((((5000 + ((state == 1) ? 1500 : 0)) + ragdoll_kind_bonus(ragdoll_kind(kind))) + ((local == 1) ? 2500 : 0)) - ((ragdoll_age_penalty(age) + ragdoll_dist_penalty(dist_mm)) + ragdoll_fade_penalty(fade_pm))), 0, 10000);
    }
}

int ragdoll_evict_ok(int newcomer_score __attribute__((unused)), int victim_score __attribute__((unused))) {
    return (newcomer_score >= victim_score);
}

