/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

int shadow_war_base_ok(int);
int shadow_war_trait_ok(int);
int shadow_war_command_ok(int);
int shadow_war_unit_power(int, int);
int shadow_war_attack_mult_tenths(int);
int shadow_war_defense_mult_tenths(int);
int shadow_war_tick_damage(int, int);
int shadow_war_side_eliminated(int);
int shadow_war_can_deploy(int);
int shadow_war_max_ticks();

int shadow_war_base_ok(int base __attribute__((unused))) {
    return ((base >= 0) && (base <= 2));
}

int shadow_war_trait_ok(int trait __attribute__((unused))) {
    return ((trait >= 0) && (trait <= 2));
}

int shadow_war_command_ok(int cmd __attribute__((unused))) {
    return ((cmd >= 0) && (cmd <= 2));
}

int shadow_war_unit_power(int base __attribute__((unused)), int trait __attribute__((unused))) {
    if ((base == 0)) {
    if ((trait == 0)) {
    return 9;
    } else {
    if ((trait == 1)) {
    return 7;
    } else {
    return 8;
    }
    }
    } else {
    if ((base == 1)) {
    if ((trait == 0)) {
    return 11;
    } else {
    if ((trait == 1)) {
    return 9;
    } else {
    return 10;
    }
    }
    } else {
    if ((trait == 0)) {
    return 13;
    } else {
    if ((trait == 1)) {
    return 16;
    } else {
    return 14;
    }
    }
    }
    }
}

int shadow_war_attack_mult_tenths(int cmd __attribute__((unused))) {
    if ((cmd == 0)) {
    return 14;
    } else {
    if ((cmd == 1)) {
    return 10;
    } else {
    return 7;
    }
    }
}

int shadow_war_defense_mult_tenths(int cmd __attribute__((unused))) {
    if ((cmd == 0)) {
    return 7;
    } else {
    if ((cmd == 1)) {
    return 14;
    } else {
    return 11;
    }
    }
}

int shadow_war_tick_damage(int attack __attribute__((unused)), int defense __attribute__((unused))) {
    if ((attack <= defense)) {
    return 1;
    } else {
    if (((attack - defense) <= 2)) {
    return 1;
    } else {
    return ((attack - defense) / 2);
    }
    }
}

int shadow_war_side_eliminated(int remaining_power __attribute__((unused))) {
    return (remaining_power <= 0);
}

int shadow_war_can_deploy(int clone_count __attribute__((unused))) {
    return (clone_count >= 1);
}

int shadow_war_max_ticks(void) {
    return 20;
}

