/* Generated by TYLER/tts/render_vh01.py from TYLER/tts/vh01_beats.tsv -- do not edit by hand.
 * Piper (a LABELED STOPGAP generator) produced the clips under assets/tyler_vo/; they are committed
 * assets (Piper is not deterministic -- never re-render in CI). The lines table, the per-beat clip
 * lengths and the HUD subtitles all come from the same TSV rows, so the subtitles can never
 * contradict what is spoken. tsv_sha256: 9de8542475f25b04b9294a48976ed9ec33ca03d60a0b57f82014b6f03dbff3f6 */

/* Per-beat length of the spoken audio = max(offset_ms + dur_ms) of that beat's lines (0 = silent).
 * tyler_coldopen.c stretches each beat's hold to fit it (PARENA tyler/voice-mod). */
static const unsigned int g_tyler_voice_clip_ms[8] = { 6274, 1277, 4394, 3773, 5857, 2322, 0, 1898 };

#define TYLER_VOICE_LINE_COUNT 8

/* { beat, speaker, offset_ms into the beat, dur_ms, committed asset path (cwd-relative) } */
#define TYLER_VOICE_LINES_INIT { \
    { 0, TYLER_ACTOR_TYLER, 0, 2305, "assets/tyler_vo/vh01_b0_tyler.wav" }, \
    { 0, TYLER_ACTOR_HANA, 2605, 3669, "assets/tyler_vo/vh01_b0_hana.wav" }, \
    { 1, TYLER_ACTOR_HANA, 0, 1277, "assets/tyler_vo/vh01_b1_hana.wav" }, \
    { 2, TYLER_ACTOR_TYLER, 0, 4394, "assets/tyler_vo/vh01_b2_tyler.wav" }, \
    { 3, TYLER_ACTOR_HANA, 0, 3773, "assets/tyler_vo/vh01_b3_hana.wav" }, \
    { 4, TYLER_ACTOR_TYLER, 0, 5857, "assets/tyler_vo/vh01_b4_tyler.wav" }, \
    { 5, TYLER_ACTOR_HANA, 0, 2322, "assets/tyler_vo/vh01_b5_hana.wav" }, \
    { 7, TYLER_ACTOR_TYLER, 0, 1898, "assets/tyler_vo/vh01_b7_tyler.wav" } \
}

/* HUD subtitle per beat: accent-stripped French [EN: gloss]. */
#define TYLER_SUBTITLE_0 "Bon. Ca, c'est nouveau. / Ne bouge pas. Compte les sorties avant de compter quoi que ce soit d'autre. [EN: Okay. This is new. / Don't move. Count the exits before you count anything else.]"
#define TYLER_SUBTITLE_1 "On n'est pas au Michigan. [EN: We're not in Michigan.]"
#define TYLER_SUBTITLE_2 "Le serveur est mort. Mais l'imprimante travaille encore. [EN: The server's dead. But the printer's still working.]"
#define TYLER_SUBTITLE_3 "Il y a quelqu'un ici. Ou il y avait quelqu'un ici il y a tres peu de temps. [EN: Someone's here. Or was, very recently.]"
#define TYLER_SUBTITLE_4 "Je ne connais pas ce langage. Et pourtant je le lis. Le code source du Cube Mecanique. [EN: I don't know this language. And yet I'm reading it. The source code for the Mecha Cube.]"
#define TYLER_SUBTITLE_5 "Non. S'il te plait. Ne le lis pas. [EN: No. Please. Don't read it.]"
#define TYLER_SUBTITLE_6 "(Tyler feeds the printout back into the printer, unread.)"
#define TYLER_SUBTITLE_7 "Je crois qu'on nous regarde. [EN: I think we're being watched.]"
