/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

int voice_plan_as_is();
int voice_plan_speed_up();
int voice_plan_stretch_hold();
int on_tyler_voice_required_hold_ms(int, int, int);
int on_tyler_voice_clip_fits(int, int);
int on_tyler_voice_speedup_permille(int, int);
int on_tyler_voice_plan(int, int, int);
int on_tyler_voice_stretched_hold_ms(int, int, int);

int voice_plan_as_is(void) {
    return 0;
}

int voice_plan_speed_up(void) {
    return 1;
}

int voice_plan_stretch_hold(void) {
    return 2;
}

int on_tyler_voice_required_hold_ms(int clip_ms __attribute__((unused)), int lead_ms __attribute__((unused)), int tail_ms __attribute__((unused))) {
    return ((clip_ms + lead_ms) + tail_ms);
}

int on_tyler_voice_clip_fits(int clip_ms __attribute__((unused)), int hold_ms __attribute__((unused))) {
    return (clip_ms <= hold_ms);
}

int on_tyler_voice_speedup_permille(int clip_ms __attribute__((unused)), int hold_ms __attribute__((unused))) {
    if ((clip_ms <= hold_ms)) {
    return 1000;
    } else {
    return ((clip_ms * 1000) / hold_ms);
    }
}

int on_tyler_voice_plan(int clip_ms __attribute__((unused)), int hold_ms __attribute__((unused)), int max_speedup_permille __attribute__((unused))) {
    if ((clip_ms <= hold_ms)) {
    return voice_plan_as_is();
    } else {
    if ((on_tyler_voice_speedup_permille(clip_ms, hold_ms) <= max_speedup_permille)) {
    return voice_plan_speed_up();
    } else {
    return voice_plan_stretch_hold();
    }
    }
}

int on_tyler_voice_stretched_hold_ms(int clip_ms __attribute__((unused)), int hold_ms __attribute__((unused)), int pad_ms __attribute__((unused))) {
    if (((clip_ms + pad_ms) > hold_ms)) {
    return (clip_ms + pad_ms);
    } else {
    return hold_ms;
    }
}

