/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

int walkie_team_channel_ext(int);
int walkie_can_hear(int, int, int);

int walkie_team_channel_ext(int team_id __attribute__((unused))) {
    if ((team_id < 0)) {
    return 2999;
    } else {
    return (3000 + team_id);
    }
}

int walkie_can_hear(int listener_team __attribute__((unused)), int speaker_team __attribute__((unused)), int distance_cm __attribute__((unused))) {
    if ((listener_team == speaker_team)) {
    return 1;
    } else {
    if ((distance_cm < 800)) {
    return 1;
    } else {
    return 0;
    }
    }
}

