/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

int silence_threshold();
int panic_arrogance_max();
int engage_arrogance_min();
int decorum_start();
int decorum_cap();
int suspicion_below();
int hysteric_below();
int wall_hp_concrete();
int breach_dps_super();
int effective_witnesses(int, int);
int witness_state(int, int, int, int);
int escalation_rank(int);
int npc_next_state(int, int, int, int, int, int);
int is_legal_transition(int, int);
int engage_outcome(int, int);
int silence_target_mask(int, int, int);
int clamp_decorum(int);
int decorum_delta(int);
int decorum_after(int, int);
int decorum_band(int);
int zone_access(int, int, int);
int conspicuousness(int, int);
int noticed(int, int, int);
int move_speed_pct(int);
int wall_max_hp(int);
int breach_dps(int, int);
int wall_hp_after(int, int, int);
int zombie_next_state(int, int, int, int, int, int);

int silence_threshold(void) {
    return 5;
}

int panic_arrogance_max(void) {
    return 15;
}

int engage_arrogance_min(void) {
    return 70;
}

int decorum_start(void) {
    return 80;
}

int decorum_cap(void) {
    return 100;
}

int suspicion_below(void) {
    return 60;
}

int hysteric_below(void) {
    return 30;
}

int wall_hp_concrete(void) {
    return 500;
}

int breach_dps_super(void) {
    return 50;
}

int effective_witnesses(int total __attribute__((unused)), int accomplices __attribute__((unused))) {
    if (((total - accomplices) < 0)) {
    return 0;
    } else {
    return (total - accomplices);
    }
}

int witness_state(int count __attribute__((unused)), int arrogance __attribute__((unused)), int compromised __attribute__((unused)), int zombie_event __attribute__((unused))) {
    if ((compromised == 1)) {
    return 2;
    } else {
    if ((count <= 0)) {
    return 0;
    } else {
    if ((arrogance <= panic_arrogance_max())) {
    return 4;
    } else {
    if ((count < silence_threshold())) {
    return 1;
    } else {
    if (((zombie_event == 1) && (arrogance >= engage_arrogance_min()))) {
    return 5;
    } else {
    return 3;
    }
    }
    }
    }
    }
}

int escalation_rank(int s __attribute__((unused))) {
    if (((s == 3) || (s == 5))) {
    return 3;
    } else {
    if (((s == 1) || (s == 4))) {
    return 1;
    } else {
    return 0;
    }
    }
}

int npc_next_state(int prev __attribute__((unused)), int count __attribute__((unused)), int arrogance __attribute__((unused)), int compromised __attribute__((unused)), int zombie_event __attribute__((unused)), int resolved __attribute__((unused))) {
    if ((prev == 2)) {
    return 2;
    } else {
    if ((compromised == 1)) {
    return 2;
    } else {
    if (((prev == 3) || (prev == 5))) {
    if ((resolved == 1)) {
    return 1;
    } else {
    if ((resolved == 2)) {
    return 0;
    } else {
    return prev;
    }
    }
    } else {
    return witness_state(count, arrogance, 0, zombie_event);
    }
    }
    }
}

int is_legal_transition(int from __attribute__((unused)), int to __attribute__((unused))) {
    if ((from == 2)) {
    return (to == 2);
    } else {
    if (((from == 3) || (from == 5))) {
    return ((to == from) || ((to == 0) || ((to == 1) || (to == 2))));
    } else {
    return 1;
    }
    }
}

int engage_outcome(int arrogance __attribute__((unused)), int tier __attribute__((unused))) {
    if ((arrogance < engage_arrogance_min())) {
    return 0;
    } else {
    if ((tier >= 1)) {
    return 1;
    } else {
    return 2;
    }
    }
}

int silence_target_mask(int attributed __attribute__((unused)), int seen_together __attribute__((unused)), int crew_mask __attribute__((unused))) {
    if ((seen_together == 1)) {
    return crew_mask;
    } else {
    if ((attributed == 0)) {
    return 1;
    } else {
    if ((attributed == 1)) {
    return 2;
    } else {
    return 4;
    }
    }
    }
}

int clamp_decorum(int d __attribute__((unused))) {
    if ((d < 0)) {
    return 0;
    } else {
    if ((d > decorum_cap())) {
    return decorum_cap();
    } else {
    return d;
    }
    }
}

int decorum_delta(int action __attribute__((unused))) {
    if ((action == 0)) {
    return 5;
    } else {
    if ((action == 1)) {
    return (0 - 25);
    } else {
    if ((action == 2)) {
    return (0 - 15);
    } else {
    if ((action == 3)) {
    return (0 - 20);
    } else {
    if ((action == 4)) {
    return (0 - 40);
    } else {
    if ((action == 5)) {
    return 1;
    } else {
    return 0;
    }
    }
    }
    }
    }
    }
}

int decorum_after(int d __attribute__((unused)), int action __attribute__((unused))) {
    return clamp_decorum((d + decorum_delta(action)));
}

int decorum_band(int d __attribute__((unused))) {
    if ((d <= 0)) {
    return 3;
    } else {
    if ((d < hysteric_below())) {
    return 2;
    } else {
    if ((d < suspicion_below())) {
    return 1;
    } else {
    return 0;
    }
    }
    }
}

int zone_access(int costume __attribute__((unused)), int zone __attribute__((unused)), int token __attribute__((unused))) {
    if ((costume == 3)) {
    return 0;
    } else {
    if ((zone == 4)) {
    if ((token > 0)) {
    return 1;
    } else {
    return 0;
    }
    } else {
    if ((zone == 0)) {
    return 1;
    } else {
    if ((zone == 1)) {
    if ((costume == 1)) {
    return 1;
    } else {
    return 0;
    }
    } else {
    if ((zone == 2)) {
    if ((costume == 0)) {
    return 1;
    } else {
    return 0;
    }
    } else {
    if ((costume == 2)) {
    return 1;
    } else {
    return 0;
    }
    }
    }
    }
    }
    }
}

int conspicuousness(int allowed __attribute__((unused)), int gear __attribute__((unused))) {
    return (((allowed == 1) ? 0 : 40) + ((gear == 1) ? 20 : 0));
}

int noticed(int vigilance __attribute__((unused)), int conspicuous __attribute__((unused)), int roll __attribute__((unused))) {
    return (roll < (((vigilance + conspicuous) > 100) ? 100 : (vigilance + conspicuous)));
}

int move_speed_pct(int tag __attribute__((unused))) {
    if ((tag == 0)) {
    return 100;
    } else {
    return 0;
    }
}

int wall_max_hp(int tag __attribute__((unused))) {
    if ((tag == 1)) {
    return wall_hp_concrete();
    } else {
    return 0;
    }
}

int breach_dps(int tag __attribute__((unused)), int tier __attribute__((unused))) {
    if ((tag == 1)) {
    if ((tier >= 1)) {
    return breach_dps_super();
    } else {
    return 0;
    }
    } else {
    return 0;
    }
}

int wall_hp_after(int hp __attribute__((unused)), int dps __attribute__((unused)), int secs __attribute__((unused))) {
    if (((hp - (dps * secs)) < 0)) {
    return 0;
    } else {
    return (hp - (dps * secs));
    }
}

int zombie_next_state(int state __attribute__((unused)), int has_target __attribute__((unused)), int tag __attribute__((unused)), int tier __attribute__((unused)), int wall_hp __attribute__((unused)), int at_edge __attribute__((unused))) {
    if ((has_target <= 0)) {
    return 0;
    } else {
    if ((state == 3)) {
    return 3;
    } else {
    if ((tag == 0)) {
    if ((at_edge == 1)) {
    return 3;
    } else {
    return 1;
    }
    } else {
    if ((tag == 1)) {
    if ((tier >= 1)) {
    if ((wall_hp <= 0)) {
    return 3;
    } else {
    return 2;
    }
    } else {
    return 4;
    }
    } else {
    return 4;
    }
    }
    }
    }
}

