/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

int phase_for_minute(int);
int weather_next(int);
int weather_min_minutes(int);
int weather_max_minutes(int);
int weather_duration(int, int);
int weather_zombie_pct(int);
int weather_sight_pct(int);
int weather_mob_damage_bonus(int);
int day_cap(int);
int night_cap(int);
int area_cap(int, int, int);
int spawn_period_minutes();
int spawn_tier(int);

int phase_for_minute(int minute __attribute__((unused))) {
    if (((minute >= 300) && (minute < 420))) {
    return 0;
    } else {
    if (((minute >= 420) && (minute < 1140))) {
    return 1;
    } else {
    if (((minute >= 1140) && (minute < 1260))) {
    return 2;
    } else {
    return 3;
    }
    }
    }
}

int weather_next(int w __attribute__((unused))) {
    return ((w + 1) % 4);
}

int weather_min_minutes(int w __attribute__((unused))) {
    if ((w == 0)) {
    return 90;
    } else {
    if ((w == 1)) {
    return 60;
    } else {
    if ((w == 2)) {
    return 45;
    } else {
    return 20;
    }
    }
    }
}

int weather_max_minutes(int w __attribute__((unused))) {
    if ((w == 0)) {
    return 240;
    } else {
    if ((w == 1)) {
    return 180;
    } else {
    if ((w == 2)) {
    return 150;
    } else {
    return 90;
    }
    }
    }
}

int weather_duration(int w __attribute__((unused)), int roll __attribute__((unused))) {
    return (weather_min_minutes(w) + (((weather_max_minutes(w) - weather_min_minutes(w)) * roll) / 99));
}

int weather_zombie_pct(int w __attribute__((unused))) {
    if ((w == 0)) {
    return 100;
    } else {
    if ((w == 1)) {
    return 110;
    } else {
    if ((w == 2)) {
    return 125;
    } else {
    return 150;
    }
    }
    }
}

int weather_sight_pct(int w __attribute__((unused))) {
    if ((w == 0)) {
    return 100;
    } else {
    if ((w == 1)) {
    return 90;
    } else {
    if ((w == 2)) {
    return 75;
    } else {
    return 50;
    }
    }
    }
}

int weather_mob_damage_bonus(int w __attribute__((unused))) {
    if ((w == 3)) {
    return 3;
    } else {
    if ((w == 2)) {
    return 1;
    } else {
    return 0;
    }
    }
}

int day_cap(int area __attribute__((unused))) {
    if ((area == 0)) {
    return 12;
    } else {
    if ((area == 1)) {
    return 4;
    } else {
    if ((area == 3)) {
    return 2;
    } else {
    return 0;
    }
    }
    }
}

int night_cap(int area __attribute__((unused))) {
    if ((area == 0)) {
    return 3;
    } else {
    return 0;
    }
}

int area_cap(int area __attribute__((unused)), int phase __attribute__((unused)), int weather __attribute__((unused))) {
    if ((phase == 3)) {
    return night_cap(area);
    } else {
    if ((phase == 1)) {
    return ((day_cap(area) * weather_zombie_pct(weather)) / 100);
    } else {
    return (((day_cap(area) / 3) * weather_zombie_pct(weather)) / 100);
    }
    }
}

int spawn_period_minutes(void) {
    return 10;
}

int spawn_tier(int roll __attribute__((unused))) {
    if ((roll < 75)) {
    return 0;
    } else {
    if ((roll < 95)) {
    return 1;
    } else {
    return 2;
    }
    }
}

