/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

int alert_should_react(int);
int alert_message_id(int, int, int);

int alert_should_react(int action_type __attribute__((unused))) {
    return ((action_type >= 101) && (action_type <= 103));
}

int alert_message_id(int action_type __attribute__((unused)), int a __attribute__((unused)), int b __attribute__((unused))) {
    if (((action_type == 101) && (b == 3))) {
    return 2;
    } else {
    if (((action_type == 101) && (b == 1))) {
    return 3;
    } else {
    if (((action_type == 102) && (b == 3))) {
    return 4;
    } else {
    if (((action_type == 103) && (b == 2))) {
    return 5;
    } else {
    return 0;
    }
    }
    }
    }
}

