/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

int zombies_awareness_should_ping(int);
int zombies_awareness_severity(int, int);

int zombies_awareness_should_ping(int action_type __attribute__((unused))) {
    return ((action_type >= 105) && (action_type <= 109));
}

int zombies_awareness_severity(int action_type __attribute__((unused)), int b __attribute__((unused))) {
    if ((action_type == 105)) {
    if ((b >= 3)) {
    return 90;
    } else {
    return 55;
    }
    } else {
    if ((action_type == 106)) {
    if ((b >= 5)) {
    return 90;
    } else {
    return 60;
    }
    } else {
    if ((action_type == 107)) {
    return 70;
    } else {
    if ((action_type == 108)) {
    return 20;
    } else {
    if ((action_type == 109)) {
    return 15;
    } else {
    return 0;
    }
    }
    }
    }
    }
}

