/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

int zombies_pheromone_should_steer_to_marker(int);

int zombies_pheromone_should_steer_to_marker(int hero_has_target __attribute__((unused))) {
    return (hero_has_target == 0);
}

