/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
/* PARENA stdlib/audio @ 09a2b7d via scripts/gen_audio_dsp.sh; parena_runtime.h not needed (scalar-only) */
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

double db_to_linear(double);
double linear_to_db(double);
double clamp_f64(double, double, double);
double lerp(double, double, double);
double mix_dry_wet(double, double, double);
double time_coef(double, double);
double one_pole_step(double, double, double);
double env_follow(double, double, double, double);
double bq_w0(double, double);
double bq_cos(double, double);
double bq_alpha(double, double, double);
double bq_amp(double);
double bq_shelf_term(double, double, double, double);
double bq_a0(int, double, double, double, double);
double bq_raw_b0(int, double, double, double, double);
double bq_raw_b1(int, double, double, double, double);
double bq_raw_b2(int, double, double, double, double);
double bq_raw_a1(int, double, double, double, double);
double bq_raw_a2(int, double, double, double, double);
double biquad_b0(int, double, double, double, double);
double biquad_b1(int, double, double, double, double);
double biquad_b2(int, double, double, double, double);
double biquad_a1(int, double, double, double, double);
double biquad_a2(int, double, double, double, double);
double biquad_tdf2_y(double, double, double);
double biquad_tdf2_s1(double, double, double, double, double);
double biquad_tdf2_s2(double, double, double, double);
double one_pole_lp_coef(double, double);
double one_pole_hp_step(double, double);
double comp_gain_db(double, double, double, double);
double expander_gain_db(double, double, double, double, double);
double limiter_gain_db(double, double);
double gain_smooth(double, double, double, double);
double deess_gain_db(double, double, double);
double kw_k1(double);
double kw_vh(void);
double kw_vb(void);
double kw_a0(double);
double kweight_shelf_b0(double);
double kweight_shelf_b1(double);
double kweight_shelf_b2(double);
double kweight_shelf_a1(double);
double kweight_shelf_a2(double);
double kw_k2(double);
double kw_hp_den(double);
double kweight_hp_a1(double);
double kweight_hp_a2(double);
double lufs_from_mean_square(double);
int lufs_absolute_gate(double);
int lufs_relative_gate(double, double);
double loudnorm_gain_db(double, double, double, double);
double sample_to_pcm16_scale(double);
double pcm16_to_sample(int);
double mixer_trim_db(double);
double mixer_eq_db(double);
double mixer_eq_low_hz(void);
double mixer_eq_mid_hz(void);
double mixer_eq_hi_hz(void);
double mixer_eq_mid_q(void);
int mixer_filter_kind(double);
double mixer_filter_freq(double);
double mixer_filter_q(double);
double mixer_fader_gain(double, int);
double xf_side_gain(double, int);
double mixer_xfader_gain(int, double, int);
double mixer_channel_gain(double, double, int, int, double, int);
double mixer_headphone(double, double, double, double);
int mixer_meter_segments(void);
int mixer_meter_segment(double);
int mixer_meter_floor_i32(double);
double mixer_peak_hold(double, double, double);
double mixer_master_limit(double, double);
double deck_tempo_range_pct(int);
double deck_pitch_pct(double, int);
double deck_rate(double, int);
double deck_bpm(double, double);
double deck_sync_rate(double, double, int);
double deck_advance(double, double, double, double);
double deck_hermite(double, double, double, double, double);
double deck_jog_bend(double, double);
double deck_scratch_rate(double);
double deck_brake_rate(double, double);
double deck_reverse_rate(double, int);
int deck_cue_press(int, double, double);
double deck_beat_len(double, double);
double deck_beat_phase(double, double, double);
double deck_quantize_pos(double, double, double, int);
double deck_loop_out(double, double, double);
double deck_loop_wrap(double, double, double, int);
double deck_loop_halve(double);
double deck_loop_double(double);
double max_beats(double, double);
double min_beats(double, double);
double deck_key_ratio(double, int, double);
int deck_at_end(double, double, double);
int mpc_pad_note(int, int);
double mpc_velocity_gain(int, int);
double mpc_ppqn(void);
double mpc_ticks_per_sample(double, double);
double mpc_grid_ticks(int);
double mpc_swing_tick(double, double, double);
double mpc_quantize_tick(double, double, double);
int mpc_repeat_due(double, double, double);
int mpc_choke(int, int);
double mpc_tune_ratio(double);
double mpc_adsr_level(double, double, double, double);
double mpc_release_level(double, double, double);
double mpc_16_levels(int, double, double);
double mpc_voice_steal_score(int, double, double);

double db_to_linear(double db __attribute__((unused))) {
    return pow((double)(10.0), (double)((db / 20.0)));
}

double linear_to_db(double lin __attribute__((unused))) {
    if ((fabs((double)(lin)) <= 0.00000000001)) {
    return -200.0;
    } else {
    return (20.0 * log10((double)(fabs((double)(lin)))));
    }
}

double clamp_f64(double x __attribute__((unused)), double lo __attribute__((unused)), double hi __attribute__((unused))) {
    if ((x < lo)) {
    return lo;
    } else {
    if ((x > hi)) {
    return hi;
    } else {
    return x;
    }
    }
}

double lerp(double a __attribute__((unused)), double b __attribute__((unused)), double t __attribute__((unused))) {
    return (a + ((b - a) * t));
}

double mix_dry_wet(double dry __attribute__((unused)), double wet __attribute__((unused)), double amount __attribute__((unused))) {
    return ((dry * (1.0 - amount)) + (wet * amount));
}

double time_coef(double ms __attribute__((unused)), double sr __attribute__((unused))) {
    if ((ms <= 0.0)) {
    return 1.0;
    } else {
    return (1.0 - exp((double)((-1.0 / ((ms * 0.001) * sr)))));
    }
}

double one_pole_step(double prev __attribute__((unused)), double x __attribute__((unused)), double coef __attribute__((unused))) {
    return (prev + (coef * (x - prev)));
}

double env_follow(double env __attribute__((unused)), double x __attribute__((unused)), double attack_coef __attribute__((unused)), double release_coef __attribute__((unused))) {
    if ((fabs((double)(x)) > env)) {
    return one_pole_step(env, fabs((double)(x)), attack_coef);
    } else {
    return one_pole_step(env, fabs((double)(x)), release_coef);
    }
}

double bq_w0(double freq __attribute__((unused)), double sr __attribute__((unused))) {
    return ((6.283185307179586 * freq) / sr);
}

double bq_cos(double freq __attribute__((unused)), double sr __attribute__((unused))) {
    return cos((double)(bq_w0(freq, sr)));
}

double bq_alpha(double freq __attribute__((unused)), double q __attribute__((unused)), double sr __attribute__((unused))) {
    return (sin((double)(bq_w0(freq, sr))) / (2.0 * q));
}

double bq_amp(double gain_db __attribute__((unused))) {
    return pow((double)(10.0), (double)((gain_db / 40.0)));
}

double bq_shelf_term(double freq __attribute__((unused)), double q __attribute__((unused)), double gain_db __attribute__((unused)), double sr __attribute__((unused))) {
    return ((2.0 * sqrt((double)(bq_amp(gain_db)))) * bq_alpha(freq, q, sr));
}

double bq_a0(int kind __attribute__((unused)), double freq __attribute__((unused)), double q __attribute__((unused)), double gain_db __attribute__((unused)), double sr __attribute__((unused))) {
    if ((kind == 4)) {
    return (1.0 + (bq_alpha(freq, q, sr) / bq_amp(gain_db)));
    } else {
    if ((kind == 5)) {
    return (((bq_amp(gain_db) + 1.0) + ((bq_amp(gain_db) - 1.0) * bq_cos(freq, sr))) + bq_shelf_term(freq, q, gain_db, sr));
    } else {
    if ((kind == 6)) {
    return (((bq_amp(gain_db) + 1.0) - ((bq_amp(gain_db) - 1.0) * bq_cos(freq, sr))) + bq_shelf_term(freq, q, gain_db, sr));
    } else {
    return (1.0 + bq_alpha(freq, q, sr));
    }
    }
    }
}

double bq_raw_b0(int kind __attribute__((unused)), double freq __attribute__((unused)), double q __attribute__((unused)), double gain_db __attribute__((unused)), double sr __attribute__((unused))) {
    if ((kind == 0)) {
    return ((1.0 - bq_cos(freq, sr)) / 2.0);
    } else {
    if ((kind == 1)) {
    return ((1.0 + bq_cos(freq, sr)) / 2.0);
    } else {
    if ((kind == 2)) {
    return bq_alpha(freq, q, sr);
    } else {
    if ((kind == 3)) {
    return 1.0;
    } else {
    if ((kind == 4)) {
    return (1.0 + (bq_alpha(freq, q, sr) * bq_amp(gain_db)));
    } else {
    if ((kind == 5)) {
    return (bq_amp(gain_db) * (((bq_amp(gain_db) + 1.0) - ((bq_amp(gain_db) - 1.0) * bq_cos(freq, sr))) + bq_shelf_term(freq, q, gain_db, sr)));
    } else {
    return (bq_amp(gain_db) * (((bq_amp(gain_db) + 1.0) + ((bq_amp(gain_db) - 1.0) * bq_cos(freq, sr))) + bq_shelf_term(freq, q, gain_db, sr)));
    }
    }
    }
    }
    }
    }
}

double bq_raw_b1(int kind __attribute__((unused)), double freq __attribute__((unused)), double q __attribute__((unused)), double gain_db __attribute__((unused)), double sr __attribute__((unused))) {
    if ((kind == 0)) {
    return (1.0 - bq_cos(freq, sr));
    } else {
    if ((kind == 1)) {
    return (0.0 - (1.0 + bq_cos(freq, sr)));
    } else {
    if ((kind == 2)) {
    return 0.0;
    } else {
    if (((kind == 3) || (kind == 4))) {
    return (-2.0 * bq_cos(freq, sr));
    } else {
    if ((kind == 5)) {
    return ((2.0 * bq_amp(gain_db)) * ((bq_amp(gain_db) - 1.0) - ((bq_amp(gain_db) + 1.0) * bq_cos(freq, sr))));
    } else {
    return ((-2.0 * bq_amp(gain_db)) * ((bq_amp(gain_db) - 1.0) + ((bq_amp(gain_db) + 1.0) * bq_cos(freq, sr))));
    }
    }
    }
    }
    }
}

double bq_raw_b2(int kind __attribute__((unused)), double freq __attribute__((unused)), double q __attribute__((unused)), double gain_db __attribute__((unused)), double sr __attribute__((unused))) {
    if ((kind == 0)) {
    return ((1.0 - bq_cos(freq, sr)) / 2.0);
    } else {
    if ((kind == 1)) {
    return ((1.0 + bq_cos(freq, sr)) / 2.0);
    } else {
    if ((kind == 2)) {
    return (0.0 - bq_alpha(freq, q, sr));
    } else {
    if ((kind == 3)) {
    return 1.0;
    } else {
    if ((kind == 4)) {
    return (1.0 - (bq_alpha(freq, q, sr) * bq_amp(gain_db)));
    } else {
    if ((kind == 5)) {
    return (bq_amp(gain_db) * (((bq_amp(gain_db) + 1.0) - ((bq_amp(gain_db) - 1.0) * bq_cos(freq, sr))) - bq_shelf_term(freq, q, gain_db, sr)));
    } else {
    return (bq_amp(gain_db) * (((bq_amp(gain_db) + 1.0) + ((bq_amp(gain_db) - 1.0) * bq_cos(freq, sr))) - bq_shelf_term(freq, q, gain_db, sr)));
    }
    }
    }
    }
    }
    }
}

double bq_raw_a1(int kind __attribute__((unused)), double freq __attribute__((unused)), double q __attribute__((unused)), double gain_db __attribute__((unused)), double sr __attribute__((unused))) {
    if ((kind == 5)) {
    return (-2.0 * ((bq_amp(gain_db) - 1.0) + ((bq_amp(gain_db) + 1.0) * bq_cos(freq, sr))));
    } else {
    if ((kind == 6)) {
    return (2.0 * ((bq_amp(gain_db) - 1.0) - ((bq_amp(gain_db) + 1.0) * bq_cos(freq, sr))));
    } else {
    return (-2.0 * bq_cos(freq, sr));
    }
    }
}

double bq_raw_a2(int kind __attribute__((unused)), double freq __attribute__((unused)), double q __attribute__((unused)), double gain_db __attribute__((unused)), double sr __attribute__((unused))) {
    if ((kind == 4)) {
    return (1.0 - (bq_alpha(freq, q, sr) / bq_amp(gain_db)));
    } else {
    if ((kind == 5)) {
    return (((bq_amp(gain_db) + 1.0) + ((bq_amp(gain_db) - 1.0) * bq_cos(freq, sr))) - bq_shelf_term(freq, q, gain_db, sr));
    } else {
    if ((kind == 6)) {
    return (((bq_amp(gain_db) + 1.0) - ((bq_amp(gain_db) - 1.0) * bq_cos(freq, sr))) - bq_shelf_term(freq, q, gain_db, sr));
    } else {
    return (1.0 - bq_alpha(freq, q, sr));
    }
    }
    }
}

double biquad_b0(int kind __attribute__((unused)), double freq __attribute__((unused)), double q __attribute__((unused)), double gain_db __attribute__((unused)), double sr __attribute__((unused))) {
    return (bq_raw_b0(kind, freq, q, gain_db, sr) / bq_a0(kind, freq, q, gain_db, sr));
}

double biquad_b1(int kind __attribute__((unused)), double freq __attribute__((unused)), double q __attribute__((unused)), double gain_db __attribute__((unused)), double sr __attribute__((unused))) {
    return (bq_raw_b1(kind, freq, q, gain_db, sr) / bq_a0(kind, freq, q, gain_db, sr));
}

double biquad_b2(int kind __attribute__((unused)), double freq __attribute__((unused)), double q __attribute__((unused)), double gain_db __attribute__((unused)), double sr __attribute__((unused))) {
    return (bq_raw_b2(kind, freq, q, gain_db, sr) / bq_a0(kind, freq, q, gain_db, sr));
}

double biquad_a1(int kind __attribute__((unused)), double freq __attribute__((unused)), double q __attribute__((unused)), double gain_db __attribute__((unused)), double sr __attribute__((unused))) {
    return (bq_raw_a1(kind, freq, q, gain_db, sr) / bq_a0(kind, freq, q, gain_db, sr));
}

double biquad_a2(int kind __attribute__((unused)), double freq __attribute__((unused)), double q __attribute__((unused)), double gain_db __attribute__((unused)), double sr __attribute__((unused))) {
    return (bq_raw_a2(kind, freq, q, gain_db, sr) / bq_a0(kind, freq, q, gain_db, sr));
}

double biquad_tdf2_y(double b0 __attribute__((unused)), double x __attribute__((unused)), double s1 __attribute__((unused))) {
    return ((b0 * x) + s1);
}

double biquad_tdf2_s1(double b1 __attribute__((unused)), double a1 __attribute__((unused)), double x __attribute__((unused)), double y __attribute__((unused)), double s2 __attribute__((unused))) {
    return (((b1 * x) - (a1 * y)) + s2);
}

double biquad_tdf2_s2(double b2 __attribute__((unused)), double a2 __attribute__((unused)), double x __attribute__((unused)), double y __attribute__((unused))) {
    return ((b2 * x) - (a2 * y));
}

double one_pole_lp_coef(double freq __attribute__((unused)), double sr __attribute__((unused))) {
    return (1.0 - exp((double)(((-6.283185307179586 * freq) / sr))));
}

double one_pole_hp_step(double x __attribute__((unused)), double lp_state __attribute__((unused))) {
    return (x - lp_state);
}

double comp_gain_db(double level_db __attribute__((unused)), double threshold_db __attribute__((unused)), double ratio __attribute__((unused)), double knee_db __attribute__((unused))) {
    if (((2.0 * (level_db - threshold_db)) < (0.0 - knee_db))) {
    return 0.0;
    } else {
    if (((knee_db > 0.0) && ((2.0 * fabs((double)((level_db - threshold_db)))) <= knee_db))) {
    return ((((1.0 / ratio) - 1.0) * pow((double)(((level_db - threshold_db) + (knee_db / 2.0))), (double)(2.0))) / (2.0 * knee_db));
    } else {
    return (((1.0 / ratio) - 1.0) * (level_db - threshold_db));
    }
    }
}

double expander_gain_db(double level_db __attribute__((unused)), double threshold_db __attribute__((unused)), double ratio __attribute__((unused)), double knee_db __attribute__((unused)), double range_db __attribute__((unused))) {
    return clamp_f64((((2.0 * (level_db - threshold_db)) > knee_db) ? 0.0 : (((knee_db > 0.0) && ((2.0 * fabs((double)((level_db - threshold_db)))) <= knee_db)) ? (((ratio - 1.0) * pow((double)(((level_db - threshold_db) - (knee_db / 2.0))), (double)(2.0))) / (-2.0 * knee_db)) : ((ratio - 1.0) * (level_db - threshold_db)))), range_db, 0.0);
}

double limiter_gain_db(double level_db __attribute__((unused)), double ceiling_db __attribute__((unused))) {
    if ((level_db > ceiling_db)) {
    return (ceiling_db - level_db);
    } else {
    return 0.0;
    }
}

double gain_smooth(double prev_db __attribute__((unused)), double target_db __attribute__((unused)), double attack_coef __attribute__((unused)), double release_coef __attribute__((unused))) {
    if ((target_db < prev_db)) {
    return one_pole_step(prev_db, target_db, attack_coef);
    } else {
    return one_pole_step(prev_db, target_db, release_coef);
    }
}

double deess_gain_db(double sib_db __attribute__((unused)), double full_db __attribute__((unused)), double intensity __attribute__((unused))) {
    if ((intensity <= 0.0)) {
    return 0.0;
    } else {
    return clamp_f64(((0.0 - intensity) * (sib_db - (full_db - 6.0))), -12.0, 0.0);
    }
}

double kw_k1(double sr __attribute__((unused))) {
    return tan((double)(((3.141592653589793 * 1681.974450955533) / sr)));
}

double kw_vh(void) {
    return pow((double)(10.0), (double)((3.999843853973347 / 20.0)));
}

double kw_vb(void) {
    return pow((double)(kw_vh()), (double)(0.4996667741545416));
}

double kw_a0(double sr __attribute__((unused))) {
    return ((1.0 + (kw_k1(sr) / 0.7071752369554196)) + (kw_k1(sr) * kw_k1(sr)));
}

double kweight_shelf_b0(double sr __attribute__((unused))) {
    return (((kw_vh() + ((kw_vb() * kw_k1(sr)) / 0.7071752369554196)) + (kw_k1(sr) * kw_k1(sr))) / kw_a0(sr));
}

double kweight_shelf_b1(double sr __attribute__((unused))) {
    return ((2.0 * ((kw_k1(sr) * kw_k1(sr)) - kw_vh())) / kw_a0(sr));
}

double kweight_shelf_b2(double sr __attribute__((unused))) {
    return (((kw_vh() - ((kw_vb() * kw_k1(sr)) / 0.7071752369554196)) + (kw_k1(sr) * kw_k1(sr))) / kw_a0(sr));
}

double kweight_shelf_a1(double sr __attribute__((unused))) {
    return ((2.0 * ((kw_k1(sr) * kw_k1(sr)) - 1.0)) / kw_a0(sr));
}

double kweight_shelf_a2(double sr __attribute__((unused))) {
    return (((1.0 - (kw_k1(sr) / 0.7071752369554196)) + (kw_k1(sr) * kw_k1(sr))) / kw_a0(sr));
}

double kw_k2(double sr __attribute__((unused))) {
    return tan((double)(((3.141592653589793 * 38.13547087602444) / sr)));
}

double kw_hp_den(double sr __attribute__((unused))) {
    return ((1.0 + (kw_k2(sr) / 0.5003270373238773)) + (kw_k2(sr) * kw_k2(sr)));
}

double kweight_hp_a1(double sr __attribute__((unused))) {
    return ((2.0 * ((kw_k2(sr) * kw_k2(sr)) - 1.0)) / kw_hp_den(sr));
}

double kweight_hp_a2(double sr __attribute__((unused))) {
    return (((1.0 - (kw_k2(sr) / 0.5003270373238773)) + (kw_k2(sr) * kw_k2(sr))) / kw_hp_den(sr));
}

double lufs_from_mean_square(double ms __attribute__((unused))) {
    if ((ms <= 0.0)) {
    return -200.0;
    } else {
    return (-0.691 + (10.0 * log10((double)(ms))));
    }
}

int lufs_absolute_gate(double block_lufs __attribute__((unused))) {
    if ((block_lufs > -70.0)) {
    return 1;
    } else {
    return 0;
    }
}

int lufs_relative_gate(double block_lufs __attribute__((unused)), double ungated_lufs __attribute__((unused))) {
    if ((block_lufs > (ungated_lufs - 10.0))) {
    return 1;
    } else {
    return 0;
    }
}

double loudnorm_gain_db(double target_lufs __attribute__((unused)), double measured_lufs __attribute__((unused)), double true_peak_db __attribute__((unused)), double ceiling_db __attribute__((unused))) {
    if (((true_peak_db + (target_lufs - measured_lufs)) > ceiling_db)) {
    return (ceiling_db - true_peak_db);
    } else {
    return (target_lufs - measured_lufs);
    }
}

double sample_to_pcm16_scale(double x __attribute__((unused))) {
    return (clamp_f64(x, -1.0, 1.0) * 32767.0);
}

double pcm16_to_sample(int s __attribute__((unused))) {
    return ((1.0 * s) / 32768.0);
}

double mixer_trim_db(double knob __attribute__((unused))) {
    if ((knob <= 0.0)) {
    return -200.0;
    } else {
    if ((knob < 0.5)) {
    return (-30.0 * (1.0 - (2.0 * knob)));
    } else {
    return (9.0 * (2.0 * (knob - 0.5)));
    }
    }
}

double mixer_eq_db(double knob __attribute__((unused))) {
    if ((knob <= 0.0)) {
    return -200.0;
    } else {
    if ((knob < 0.5)) {
    return (-26.0 * (1.0 - (2.0 * knob)));
    } else {
    return (6.0 * (2.0 * (knob - 0.5)));
    }
    }
}

double mixer_eq_low_hz(void) {
    return 70.0;
}

double mixer_eq_mid_hz(void) {
    return 1000.0;
}

double mixer_eq_hi_hz(void) {
    return 13000.0;
}

double mixer_eq_mid_q(void) {
    return 0.7;
}

int mixer_filter_kind(double knob __attribute__((unused))) {
    if ((knob < -0.03)) {
    return 0;
    } else {
    if ((knob > 0.03)) {
    return 1;
    } else {
    return -1;
    }
    }
}

double mixer_filter_freq(double knob __attribute__((unused))) {
    if ((knob < -0.03)) {
    return (20000.0 * pow((double)((60.0 / 20000.0)), (double)(((fabs((double)(knob)) - 0.03) / 0.97))));
    } else {
    if ((knob > 0.03)) {
    return (20.0 * pow((double)((8000.0 / 20.0)), (double)(((knob - 0.03) / 0.97))));
    } else {
    return 20000.0;
    }
    }
}

double mixer_filter_q(double knob __attribute__((unused))) {
    return (0.707 + (1.8 * fabs((double)(knob))));
}

double mixer_fader_gain(double pos __attribute__((unused)), int curve __attribute__((unused))) {
    if ((pos <= 0.0)) {
    return 0.0;
    } else {
    if ((pos >= 1.0)) {
    return 1.0;
    } else {
    if ((curve == 0)) {
    return ((pos * pos) * pos);
    } else {
    if ((curve == 2)) {
    return sqrt((double)(pos));
    } else {
    return (pos * pos);
    }
    }
    }
    }
}

double xf_side_gain(double dist __attribute__((unused)), int curve __attribute__((unused))) {
    if ((curve == 0)) {
    return cos((double)((dist * 1.5707963267948966)));
    } else {
    if ((curve == 1)) {
    return (1.0 - dist);
    } else {
    if ((dist >= 0.97)) {
    return 0.0;
    } else {
    return 1.0;
    }
    }
    }
}

double mixer_xfader_gain(int assign __attribute__((unused)), double pos __attribute__((unused)), int curve __attribute__((unused))) {
    if ((assign == 1)) {
    return 1.0;
    } else {
    if ((assign == 0)) {
    return xf_side_gain(clamp_f64(pos, 0.0, 1.0), curve);
    } else {
    return xf_side_gain((1.0 - clamp_f64(pos, 0.0, 1.0)), curve);
    }
    }
}

double mixer_channel_gain(double trim_knob __attribute__((unused)), double fader_pos __attribute__((unused)), int fader_curve __attribute__((unused)), int assign __attribute__((unused)), double xf_pos __attribute__((unused)), int xf_curve __attribute__((unused))) {
    return ((db_to_linear(mixer_trim_db(trim_knob)) * mixer_fader_gain(fader_pos, fader_curve)) * mixer_xfader_gain(assign, xf_pos, xf_curve));
}

double mixer_headphone(double cue __attribute__((unused)), double master __attribute__((unused)), double mix __attribute__((unused)), double level __attribute__((unused))) {
    return (level * ((cue * cos((double)((mix * 1.5707963267948966)))) + (master * sin((double)((mix * 1.5707963267948966))))));
}

int mixer_meter_segments(void) {
    return 15;
}

int mixer_meter_segment(double level_db __attribute__((unused))) {
    if ((level_db < -24.0)) {
    return 0;
    } else {
    if ((level_db >= 3.0)) {
    return 15;
    } else {
    return (1 + mixer_meter_floor_i32((((level_db + 24.0) / 27.0) * 14.0)));
    }
    }
}

int mixer_meter_floor_i32(double x __attribute__((unused))) {
    if ((x >= 14.0)) {
    return 14;
    } else {
    if ((x >= 13.0)) {
    return 13;
    } else {
    if ((x >= 12.0)) {
    return 12;
    } else {
    if ((x >= 11.0)) {
    return 11;
    } else {
    if ((x >= 10.0)) {
    return 10;
    } else {
    if ((x >= 9.0)) {
    return 9;
    } else {
    if ((x >= 8.0)) {
    return 8;
    } else {
    if ((x >= 7.0)) {
    return 7;
    } else {
    if ((x >= 6.0)) {
    return 6;
    } else {
    if ((x >= 5.0)) {
    return 5;
    } else {
    if ((x >= 4.0)) {
    return 4;
    } else {
    if ((x >= 3.0)) {
    return 3;
    } else {
    if ((x >= 2.0)) {
    return 2;
    } else {
    if ((x >= 1.0)) {
    return 1;
    } else {
    return 0;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
}

double mixer_peak_hold(double held_db __attribute__((unused)), double level_db __attribute__((unused)), double fall_db __attribute__((unused))) {
    if ((level_db > held_db)) {
    return level_db;
    } else {
    return (held_db - fall_db);
    }
}

double mixer_master_limit(double level_db __attribute__((unused)), double ceiling_db __attribute__((unused))) {
    return limiter_gain_db(level_db, ceiling_db);
}

double deck_tempo_range_pct(int sel __attribute__((unused))) {
    if ((sel == 0)) {
    return 6.0;
    } else {
    if ((sel == 1)) {
    return 10.0;
    } else {
    if ((sel == 2)) {
    return 16.0;
    } else {
    return 100.0;
    }
    }
    }
}

double deck_pitch_pct(double fader __attribute__((unused)), int range_sel __attribute__((unused))) {
    return (clamp_f64(fader, -1.0, 1.0) * deck_tempo_range_pct(range_sel));
}

double deck_rate(double fader __attribute__((unused)), int range_sel __attribute__((unused))) {
    return (1.0 + (deck_pitch_pct(fader, range_sel) / 100.0));
}

double deck_bpm(double track_bpm __attribute__((unused)), double rate __attribute__((unused))) {
    return (track_bpm * rate);
}

double deck_sync_rate(double master_bpm __attribute__((unused)), double track_bpm __attribute__((unused)), int range_sel __attribute__((unused))) {
    if ((track_bpm <= 0.0)) {
    return 1.0;
    } else {
    return clamp_f64((master_bpm / track_bpm), (1.0 - (deck_tempo_range_pct(range_sel) / 100.0)), (1.0 + (deck_tempo_range_pct(range_sel) / 100.0)));
    }
}

double deck_advance(double pos __attribute__((unused)), double rate __attribute__((unused)), double src_sr __attribute__((unused)), double out_sr __attribute__((unused))) {
    return (pos + (rate * (src_sr / out_sr)));
}

double deck_hermite(double x0 __attribute__((unused)), double x1 __attribute__((unused)), double x2 __attribute__((unused)), double x3 __attribute__((unused)), double t __attribute__((unused))) {
    return (((((((((0.5 * (x3 - x0)) - (1.5 * (x2 - x1))) + 0.0) * t) + (((x0 + (2.0 * x2)) - (2.5 * x1)) + (-0.5 * x3))) * t) + (0.5 * (x2 - x0))) * t) + x1);
}

double deck_jog_bend(double rate __attribute__((unused)), double jog_rev_per_sec __attribute__((unused))) {
    return (rate * (1.0 + clamp_f64((jog_rev_per_sec * 0.25), -0.5, 0.5)));
}

double deck_scratch_rate(double jog_rev_per_sec __attribute__((unused))) {
    return (jog_rev_per_sec / 0.5555555555555556);
}

double deck_brake_rate(double rate __attribute__((unused)), double coef __attribute__((unused))) {
    if ((fabs((double)((rate - (rate * coef)))) < 0.001)) {
    return 0.0;
    } else {
    return (rate - (rate * coef));
    }
}

double deck_reverse_rate(double rate __attribute__((unused)), int reverse __attribute__((unused))) {
    if ((reverse == 1)) {
    return (0.0 - rate);
    } else {
    return rate;
    }
}

int deck_cue_press(int playing __attribute__((unused)), double pos __attribute__((unused)), double cue_pos __attribute__((unused))) {
    if ((playing == 1)) {
    return 2;
    } else {
    if ((fabs((double)((pos - cue_pos))) < 1.0)) {
    return 3;
    } else {
    return 1;
    }
    }
}

double deck_beat_len(double bpm __attribute__((unused)), double src_sr __attribute__((unused))) {
    if ((bpm <= 0.0)) {
    return 0.0;
    } else {
    return ((60.0 / bpm) * src_sr);
    }
}

double deck_beat_phase(double pos __attribute__((unused)), double grid_offset __attribute__((unused)), double beat_len __attribute__((unused))) {
    if ((beat_len <= 0.0)) {
    return 0.0;
    } else {
    return (((pos - grid_offset) / beat_len) - floor((double)(((pos - grid_offset) / beat_len))));
    }
}

double deck_quantize_pos(double pos __attribute__((unused)), double grid_offset __attribute__((unused)), double beat_len __attribute__((unused)), int quantize __attribute__((unused))) {
    if (((quantize == 0) || (beat_len <= 0.0))) {
    return pos;
    } else {
    return (grid_offset + (beat_len * floor((double)((((pos - grid_offset) / beat_len) + 0.5)))));
    }
}

double deck_loop_out(double loop_in __attribute__((unused)), double beats __attribute__((unused)), double beat_len __attribute__((unused))) {
    return (loop_in + (beats * beat_len));
}

double deck_loop_wrap(double pos __attribute__((unused)), double loop_in __attribute__((unused)), double loop_out __attribute__((unused)), int active __attribute__((unused))) {
    if (((active == 0) || (loop_out <= loop_in))) {
    return pos;
    } else {
    if ((pos >= loop_out)) {
    return (loop_in + (pos - loop_out));
    } else {
    if ((pos < loop_in)) {
    return (loop_out - (loop_in - pos));
    } else {
    return pos;
    }
    }
    }
}

double deck_loop_halve(double beats __attribute__((unused))) {
    return max_beats((beats / 2.0), 0.03125);
}

double deck_loop_double(double beats __attribute__((unused))) {
    return min_beats((beats * 2.0), 32.0);
}

double max_beats(double a __attribute__((unused)), double b __attribute__((unused))) {
    if ((a > b)) {
    return a;
    } else {
    return b;
    }
}

double min_beats(double a __attribute__((unused)), double b __attribute__((unused))) {
    if ((a < b)) {
    return a;
    } else {
    return b;
    }
}

double deck_key_ratio(double rate __attribute__((unused)), int master_tempo __attribute__((unused)), double semitones __attribute__((unused))) {
    return ((((master_tempo == 1) && (fabs((double)(rate)) > 0.0)) ? (1.0 / fabs((double)(rate))) : 1.0) * pow((double)(2.0), (double)((semitones / 12.0))));
}

int deck_at_end(double pos __attribute__((unused)), double length __attribute__((unused)), double rate __attribute__((unused))) {
    if (((rate > 0.0) && (pos >= (length - 2.0)))) {
    return 1;
    } else {
    if (((rate < 0.0) && (pos <= 1.0))) {
    return 1;
    } else {
    return 0;
    }
    }
}

int mpc_pad_note(int bank __attribute__((unused)), int pad __attribute__((unused))) {
    return (36 + ((bank * 16) + pad));
}

double mpc_velocity_gain(int velocity __attribute__((unused)), int full __attribute__((unused))) {
    if ((full == 1)) {
    return 1.0;
    } else {
    if ((velocity <= 0)) {
    return 0.0;
    } else {
    return pow((double)(((1.0 * ((velocity > 127) ? 127 : velocity)) / 127.0)), (double)(1.6));
    }
    }
}

double mpc_ppqn(void) {
    return 960.0;
}

double mpc_ticks_per_sample(double bpm __attribute__((unused)), double sr __attribute__((unused))) {
    return ((bpm * 960.0) / (60.0 * sr));
}

double mpc_grid_ticks(int grid __attribute__((unused))) {
    if ((grid == 0)) {
    return 480.0;
    } else {
    if ((grid == 1)) {
    return 320.0;
    } else {
    if ((grid == 2)) {
    return 240.0;
    } else {
    if ((grid == 3)) {
    return 160.0;
    } else {
    if ((grid == 4)) {
    return 120.0;
    } else {
    return 80.0;
    }
    }
    }
    }
    }
}

double mpc_swing_tick(double tick __attribute__((unused)), double grid_ticks __attribute__((unused)), double swing_pct __attribute__((unused))) {
    if ((floor((double)((tick / grid_ticks))) == (2.0 * floor((double)((tick / (2.0 * grid_ticks))))))) {
    return tick;
    } else {
    return (tick + (grid_ticks * ((2.0 * (clamp_f64(swing_pct, 50.0, 75.0) / 100.0)) - 1.0)));
    }
}

double mpc_quantize_tick(double tick __attribute__((unused)), double grid_ticks __attribute__((unused)), double strength_pct __attribute__((unused))) {
    return (tick + ((strength_pct / 100.0) * ((grid_ticks * floor((double)(((tick / grid_ticks) + 0.5)))) - tick)));
}

int mpc_repeat_due(double prev_tick __attribute__((unused)), double tick __attribute__((unused)), double grid_ticks __attribute__((unused))) {
    if ((floor((double)((tick / grid_ticks))) > floor((double)((prev_tick / grid_ticks))))) {
    return 1;
    } else {
    return 0;
    }
}

int mpc_choke(int new_group __attribute__((unused)), int voice_group __attribute__((unused))) {
    if (((new_group > 0) && (new_group == voice_group))) {
    return 1;
    } else {
    return 0;
    }
}

double mpc_tune_ratio(double semitones __attribute__((unused))) {
    return pow((double)(2.0), (double)((semitones / 12.0)));
}

double mpc_adsr_level(double t_ms __attribute__((unused)), double attack_ms __attribute__((unused)), double decay_ms __attribute__((unused)), double sustain __attribute__((unused))) {
    if ((t_ms < attack_ms)) {
    return (t_ms / attack_ms);
    } else {
    if (((t_ms - attack_ms) < decay_ms)) {
    return (sustain + ((1.0 - sustain) * (1.0 - ((t_ms - attack_ms) / decay_ms))));
    } else {
    return sustain;
    }
    }
}

double mpc_release_level(double t_since_off_ms __attribute__((unused)), double level_at_off __attribute__((unused)), double release_ms __attribute__((unused))) {
    if ((t_since_off_ms >= release_ms)) {
    return 0.0;
    } else {
    return (level_at_off * (1.0 - (t_since_off_ms / release_ms)));
    }
}

double mpc_16_levels(int pad __attribute__((unused)), double lo __attribute__((unused)), double hi __attribute__((unused))) {
    return (lo + (((1.0 * pad) / 15.0) * (hi - lo)));
}

double mpc_voice_steal_score(int released __attribute__((unused)), double level __attribute__((unused)), double age_ms __attribute__((unused))) {
    return ((((released == 1) ? 0.0 : 10.0) + level) - (age_ms / 100000.0));
}

