/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

int edu_slot_count();
int edu_seed_slot(int, int);
int edu_compile_slot(int);
int edu_run_slot(int);
int edu_slot_compiled(int);
int edu_gate_open();
int edu_bridge_raised();
int edu_portal_open();
int edu_portal_stability();
int edu_crate_x();
int edu_last_print();
void edu_reset_world();
int edu_trial_complete(int, int, int, int);
int edu_trial_step(int);

int edu_slot_count(void) {
    return (eduvm_host_slot_count());
}

int edu_seed_slot(int slot __attribute__((unused)), int preset __attribute__((unused))) {
    return (eduvm_host_seed_slot(slot, preset));
}

int edu_compile_slot(int slot __attribute__((unused))) {
    return (eduvm_host_compile_slot(slot));
}

int edu_run_slot(int slot __attribute__((unused))) {
    return (eduvm_host_run_slot(slot));
}

int edu_slot_compiled(int slot __attribute__((unused))) {
    return (eduvm_host_slot_compiled(slot));
}

int edu_gate_open(void) {
    return (eduvm_host_world(0));
}

int edu_bridge_raised(void) {
    return (eduvm_host_world(1));
}

int edu_portal_open(void) {
    return (eduvm_host_world(2));
}

int edu_portal_stability(void) {
    return (eduvm_host_world(3));
}

int edu_crate_x(void) {
    return (eduvm_host_world(4));
}

int edu_last_print(void) {
    return (eduvm_host_world(5));
}

void edu_reset_world(void) {
    eduvm_host_reset_world();
}

int edu_trial_complete(int gate __attribute__((unused)), int bridge __attribute__((unused)), int portal_open __attribute__((unused)), int stability __attribute__((unused))) {
    if ((((gate == 1) && (bridge == 1)) && ((portal_open == 1) && (stability >= 100)))) {
    return 1;
    } else {
    return 0;
    }
}

int edu_trial_step(int slot __attribute__((unused))) {
    if ((edu_compile_slot(slot) == 1)) {
    if ((edu_run_slot(slot) == 1)) {
    return edu_trial_complete(edu_gate_open(), edu_bridge_raised(), edu_portal_open(), edu_portal_stability());
    } else {
    return 0;
    }
    } else {
    return 0;
    }
}

