/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

void reflux_dispatch(int, int, int, int);
int reflux_log_size();
int reflux_action_type_at(int);
int reflux_action_a_at(int);
int reflux_action_b_at(int);
int reflux_action_c_at(int);

void reflux_dispatch(int action_type __attribute__((unused)), int a __attribute__((unused)), int b __attribute__((unused)), int c __attribute__((unused))) {
    reflux_host_dispatch(action_type, a, b, c);
}

int reflux_log_size(void) {
    return (reflux_host_log_size());
}

int reflux_action_type_at(int index __attribute__((unused))) {
    return (reflux_host_action_type_at(index));
}

int reflux_action_a_at(int index __attribute__((unused))) {
    return (reflux_host_action_a_at(index));
}

int reflux_action_b_at(int index __attribute__((unused))) {
    return (reflux_host_action_b_at(index));
}

int reflux_action_c_at(int index __attribute__((unused))) {
    return (reflux_host_action_c_at(index));
}

