#!/usr/bin/env python3
"""bake_levels.py -- card #479: bake every IDUNA/NOCK level into the binary.

Fetches the main shankpit-levels registry (list + every level's export) and the ZOMBIES collection's
default level from a live IDUNA, and writes packages/world/baked_levels_gen.h. level_boxes.h serves
level_boxes_fetch_registry_list_in / level_boxes_fetch_export from these tables unless the player turned
on LIVE LEVEL DOWNLOAD in the top-level SETTINGS menu (then it prefers the network and falls back to the
baked copy). Re-run after a level is added/changed in NOCK, review the diff, commit it.

  python3 scripts/bake_levels.py [--base http://127.0.0.1:8080] [--out packages/world/baked_levels_gen.h]

Output is deterministic (sorted by id, compact JSON) so an unchanged registry produces a byte-identical file.
"""
import argparse, json, sys, urllib.error, urllib.request

ap = argparse.ArgumentParser()
ap.add_argument("--base", default="http://127.0.0.1:8080")
ap.add_argument("--out", default="packages/world/baked_levels_gen.h")
args = ap.parse_args()
API = args.base.rstrip("/") + "/api/v1/shankpit-levels"


def get(url):
    with urllib.request.urlopen(url, timeout=20) as r:
        return r.read().decode("utf-8")


def c_literal(s, indent="    "):
    out = []
    for i in range(0, len(s), 100):
        chunk = s[i:i + 100].replace("\\", "\\\\").replace('"', '\\"')
        out.append(indent + '"' + chunk + '"')
    return "\n".join(out) if out else indent + '""'


main = sorted(json.loads(get(API)), key=lambda e: e["id"])
zom = [e for e in json.loads(get(API + "?collection=zombies")) if e.get("is_zombie_default")]
zom = sorted(zom, key=lambda e: e["id"])

exports = {}
for e in main + zom:
    try:
        exports[e["id"]] = json.dumps(json.loads(get("%s/%d/export" % (API, e["id"]))), separators=(",", ":"))
    except urllib.error.HTTPError as err:
        # e.g. "composed level too many boxes after flattening" -- the live registry lists it but cannot
        # export it either. A baked list must not offer a level the baked table cannot load.
        print("skipping level %d (%s): export HTTP %d" % (e["id"], e.get("name"), err.code), file=sys.stderr)
main = [e for e in main if e["id"] in exports]
zom = [e for e in zom if e["id"] in exports]

lines = [
    "/* baked_levels_gen.h -- GENERATED by scripts/bake_levels.py (card #479). Do not edit by hand.",
    " * %d main-registry levels + %d ZOMBIES default level(s), baked from %s." % (len(main), len(zom), args.base),
    " * Served by level_boxes.h unless LIVE LEVEL DOWNLOAD is on (SETTINGS menu). */",
    "#ifndef SHANKPIT_BAKED_LEVELS_GEN_H",
    "#define SHANKPIT_BAKED_LEVELS_GEN_H",
    "",
    "static const char BAKED_REGISTRY_MAIN[] =",
    c_literal(json.dumps(main, separators=(",", ":"))) + ";",
    "",
    "static const char BAKED_REGISTRY_ZOMBIES[] =",
    c_literal(json.dumps(zom, separators=(",", ":"))) + ";",
    "",
    "typedef struct { int id; const char *json; } BakedLevelExport;",
    "static const BakedLevelExport BAKED_LEVEL_EXPORTS[] = {",
]
for lid in sorted(exports):
    lines.append("    { %d," % lid)
    lines.append(c_literal(exports[lid], "      ") + " },")
lines += ["};", "#define BAKED_LEVEL_EXPORT_COUNT %d" % len(exports), "", "#endif", ""]
open(args.out, "w").write("\n".join(lines))
print("baked %d levels (%d main, %d zombies) -> %s" % (len(exports), len(main), len(zom), args.out))
