#!/usr/bin/env bash
# gen_audio_dsp.sh -- regenerate packages/audio/audio_dsp_gen.{c,h} from PARENA stdlib/audio.
#
# The engine's sound-engineering math (biquads, dynamics, loudness, DJ mixer/deck/sampler curves)
# is authored once in PARENA (stdlib/audio/{dsp,mixer4,deck,sampler}.prn) and compiled here to C
# by the real `parena` compiler; IDUNA's NOCK compiles the same files to TypeScript. Committed --
# a normal build never needs PARENA. Usage: PARENA_DIR=../PARENA scripts/gen_audio_dsp.sh
set -euo pipefail
root="$(cd "$(dirname "$0")/.." && pwd)"
parena_dir="${PARENA_DIR:-$root/../PARENA}"
[ -x "$parena_dir/parena" ] || { echo "gen_audio_dsp: build $parena_dir/parena first" >&2; exit 1; }
a="$parena_dir/stdlib/audio"
out="$root/packages/audio/audio_dsp_gen.c"
"$parena_dir/parena" build "$a/dsp.prn" "$a/mixer4.prn" "$a/deck.prn" "$a/sampler.prn" -o "$out" >/dev/null
rev="$(git -C "$parena_dir" rev-parse --short HEAD 2>/dev/null || echo unknown)"
# scalar-only output needs only <math.h>; drop the runtime include (it pulls SDL2/arena headers)
sed -i "s|^#include \"parena_runtime.h\"$|/* PARENA stdlib/audio @ $rev via scripts/gen_audio_dsp.sh; parena_runtime.h not needed (scalar-only) */|" "$out"
sed -i -E 's/^(double|int) ([a-z0-9_]+)\(\)( \{|;)$/\1 \2(void)\3/' "$out"
hdr="$root/packages/audio/audio_dsp_gen.h"
{
  echo "/* Generated by scripts/gen_audio_dsp.sh from PARENA stdlib/audio @ $rev -- do not edit. */"
  echo "#ifndef AUDIO_DSP_GEN_H"
  echo "#define AUDIO_DSP_GEN_H"
  grep -E '^(double|int) [a-z0-9_]+\(.*\);$' "$out"
  echo "#endif"
} > "$hdr"
echo "gen_audio_dsp: wrote $out, $hdr"
