#!/usr/bin/env bash
# gen_ui_menu.sh -- regenerate packages/ui/menu_gen.{c,h} from PARENA stdlib/ui/menu.prn (card #483).
#
# The shared grid-menu logic (nav, hit-test, double-click timing) is authored once in PARENA and
# compiled here to C by the real `parena` compiler; apps/lobby calls it instead of its own copies.
# Committed -- a normal build never needs PARENA. PARENA's tests/test_ui_menu.c proves it matches the
# original lobby C everywhere. Usage: PARENA_DIR=../PARENA scripts/gen_ui_menu.sh
set -euo pipefail
root="$(cd "$(dirname "$0")/.." && pwd)"
parena_dir="${PARENA_DIR:-$root/../PARENA}"
[ -x "$parena_dir/parena" ] || { echo "gen_ui_menu: build $parena_dir/parena first" >&2; exit 1; }
out="$root/packages/ui/menu_gen.c"
"$parena_dir/parena" build "$parena_dir/stdlib/ui/menu.prn" -o "$out" >/dev/null
rev="$(git -C "$parena_dir" rev-parse --short HEAD 2>/dev/null || echo unknown)"
# scalar-only output needs only <math.h>; drop the runtime include (it pulls SDL2/arena headers)
sed -i "s|^#include \"parena_runtime.h\"$|/* PARENA stdlib/ui/menu.prn @ $rev via scripts/gen_ui_menu.sh; parena_runtime.h not needed (scalar-only) */|" "$out"
hdr="$root/packages/ui/menu_gen.h"
{
  echo "/* Generated by scripts/gen_ui_menu.sh from PARENA stdlib/ui/menu.prn @ $rev -- do not edit. */"
  echo "#ifndef UI_MENU_GEN_H"
  echo "#define UI_MENU_GEN_H"
  grep -E '^(double|int) (menu_[a-z0-9_]+)\(.*\);$' "$out"
  echo "#endif"
} > "$hdr"
echo "gen_ui_menu: wrote $out, $hdr"
