#!/usr/bin/env bash
# gen_bullet_holes.sh -- regenerate packages/world/bullet_hole_gen.h from NOCK's texture library.
#
# SHANKPIT's per-gun bullet-hole decals (founder real-time, 2026-10-01: "using the nock tools
# parena texture generator and database") are authored in PARENA (PARENA/stdlib/shankpit/textures/
# bullet_hole_<gun>.prn), rendered and stored by NOCK as `bullet-hole-<gun>` rows in IDUNA's
# nock_textures table (IDUNA cmd/nock_gen_textures), and served at runtime by IDUNA's public
# GET /api/v1/nock-textures/by-name/<name>/image. This script exports those same PNGs into a
# checked-in header so the client has the real NOCK textures offline / before IDUNA is deployed
# with that route; the client prefers a live fetch and falls back to these bytes.
# Usage: NOCK_DB=../IDUNA/var/iduna.db scripts/gen_bullet_holes.sh   (read-only on the DB)
set -euo pipefail
root="$(cd "$(dirname "$0")/.." && pwd)"
db="${NOCK_DB:-$root/../IDUNA/var/iduna.db}"
out="$root/packages/world/bullet_hole_gen.h"
tmp="$(mktemp -d)"; trap 'rm -rf "$tmp"' EXIT
{
  echo "/* Generated by scripts/gen_bullet_holes.sh from NOCK's nock_textures table -- do not edit. */"
  echo "#ifndef SHANKPIT_BULLET_HOLE_GEN_H"
  echo "#define SHANKPIT_BULLET_HOLE_GEN_H"
  for gun in magnum ar shotgun sniper; do
    sqlite3 -readonly "$db" "select hex(png_data) from nock_textures where name='bullet-hole-$gun'" | xxd -r -p > "$tmp/$gun.png"
    [ -s "$tmp/$gun.png" ] || { echo "gen_bullet_holes: bullet-hole-$gun not found in $db" >&2; exit 1; }
    echo "static const unsigned char g_bullet_hole_png_$gun[] = {"
    xxd -i < "$tmp/$gun.png"
    echo "};"
    echo "static const unsigned int g_bullet_hole_png_${gun}_len = $(wc -c < "$tmp/$gun.png");"
  done
  echo "#endif"
} > "$out"
echo "gen_bullet_holes: wrote $out"
