/* Generated by scripts/gen_ui_menu.sh from PARENA stdlib/ui/menu.prn @ ee80527 -- do not edit. */
#ifndef UI_MENU_GEN_H
#define UI_MENU_GEN_H
int menu_col(int, int);
int menu_row(int, int);
int menu_rows(int, int);
double menu_times_f64(double, int);
double menu_cell_x(int, int, double, double);
double menu_cell_y(int, int, double, double);
int menu_nav_move(int, int, int, int, int);
int menu_hit_test(double, double, int, int, double, double, double, double, double);
int menu_click_kind(int, int, int, int);
int menu_cycle(int, int);
#endif
