/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
/* PARENA stdlib/ui/menu.prn @ ee80527 via scripts/gen_ui_menu.sh; parena_runtime.h not needed (scalar-only) */
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

int menu_col(int, int);
int menu_row(int, int);
int menu_rows(int, int);
double menu_times_f64(double, int);
double menu_cell_x(int, int, double, double);
double menu_cell_y(int, int, double, double);
int menu_nav_move(int, int, int, int, int);
int menu_hit_test(double, double, int, int, double, double, double, double, double);
int menu_click_kind(int, int, int, int);
int menu_cycle(int, int);

int menu_col(int idx __attribute__((unused)), int cols __attribute__((unused))) {
    return (idx % cols);
}

int menu_row(int idx __attribute__((unused)), int cols __attribute__((unused))) {
    return (idx / cols);
}

int menu_rows(int count __attribute__((unused)), int cols __attribute__((unused))) {
    return ((count + (cols - 1)) / cols);
}

double menu_times_f64(double a __attribute__((unused)), int n __attribute__((unused))) {
    double __loop_result_0 __attribute__((unused));
    int i = 0;
    double acc = 0.0;
    while (1) {
        if ((i >= n)) {
        __loop_result_0 = acc;
        break;
        } else {
        int __recur_tmp_0 = (i + 1);
        double __recur_tmp_1 = (acc + a);
        i = __recur_tmp_0;
        acc = __recur_tmp_1;
        continue;
        }
    }
    return __loop_result_0;
}

double menu_cell_x(int idx __attribute__((unused)), int cols __attribute__((unused)), double menu_x __attribute__((unused)), double col_w __attribute__((unused))) {
    return (menu_x + menu_times_f64(col_w, menu_col(idx, cols)));
}

double menu_cell_y(int idx __attribute__((unused)), int cols __attribute__((unused)), double menu_y __attribute__((unused)), double row_gap __attribute__((unused))) {
    return (menu_y - menu_times_f64(row_gap, menu_row(idx, cols)));
}

int menu_nav_move(int sel __attribute__((unused)), int count __attribute__((unused)), int cols __attribute__((unused)), int dx __attribute__((unused)), int dy __attribute__((unused))) {
    if ((count <= 0)) {
    return 0;
    } else {
    if ((!((dx == 0)))) {
    int idx __attribute__((unused)) = ((menu_row(sel, cols) * cols) + (((menu_col(sel, cols) + dx) + cols) % cols));
    if ((idx >= count)) {
    if (((menu_row(sel, cols) * cols) >= count)) {
    return (count - 1);
    } else {
    return (menu_row(sel, cols) * cols);
    }
    } else {
    return idx;
    }
    } else {
    if ((!((dy == 0)))) {
    int rows __attribute__((unused)) = menu_rows(count, cols);
    int idx __attribute__((unused)) = (((((menu_row(sel, cols) + dy) + rows) % rows) * cols) + menu_col(sel, cols));
    if ((idx >= count)) {
    return (count - 1);
    } else {
    return idx;
    }
    } else {
    return sel;
    }
    }
    }
}

int menu_hit_test(double mx __attribute__((unused)), double my __attribute__((unused)), int count __attribute__((unused)), int cols __attribute__((unused)), double menu_x __attribute__((unused)), double menu_y __attribute__((unused)), double col_w __attribute__((unused)), double row_gap __attribute__((unused)), double icon __attribute__((unused))) {
    int __loop_result_1 __attribute__((unused));
    int i = 0;
    while (1) {
        if ((i >= count)) {
        __loop_result_1 = -1;
        break;
        } else {
        double x __attribute__((unused)) = menu_cell_x(i, cols, menu_x, col_w);
        double y __attribute__((unused)) = menu_cell_y(i, cols, menu_y, row_gap);
        if ((((mx >= x) && (mx <= (x + icon))) && ((my >= y) && (my <= (y + icon))))) {
        __loop_result_1 = i;
        break;
        } else {
        int __recur_tmp_0 = (i + 1);
        i = __recur_tmp_0;
        continue;
        }
        }
    }
    return __loop_result_1;
}

int menu_click_kind(int last_idx __attribute__((unused)), int last_ms __attribute__((unused)), int idx __attribute__((unused)), int now __attribute__((unused))) {
    if (((last_idx == idx) && (last_ms > 0))) {
    if (((now - last_ms) <= 250)) {
    return 1;
    } else {
    if (((now - last_ms) <= 700)) {
    return 2;
    } else {
    return 0;
    }
    }
    } else {
    return 0;
    }
}

int menu_cycle(int cur __attribute__((unused)), int n __attribute__((unused))) {
    return ((cur + 1) % n);
}

