/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

int cam_reaction_ms(int);
int cam_smooth_step(int, int, int, int);
int cam_lead_milli(int, int);
int cam_action_score(int, int, int, int, int);
int cam_should_cut(int, int, int, int, int);
int cam_tri(int, int);
int cam_shake_milli(int, int);
int cam_orbit_angle_milli(int, int);
int cam_fov_milli(int);

int cam_reaction_ms(int skill_permille __attribute__((unused))) {
    return (700 - ((580 * ((skill_permille < 0) ? 0 : ((skill_permille > 1000) ? 1000 : skill_permille))) / 1000));
}

int cam_smooth_step(int pos __attribute__((unused)), int target __attribute__((unused)), int dt_ms __attribute__((unused)), int tau_ms __attribute__((unused))) {
    return (pos + (((target - pos) * dt_ms) / (tau_ms + dt_ms)));
}

int cam_lead_milli(int velocity __attribute__((unused)), int lead_ms __attribute__((unused))) {
    return ((velocity * lead_ms) / 1000);
}

int cam_action_score(int dist_enemy __attribute__((unused)), int speed __attribute__((unused)), int since_kill_ms __attribute__((unused)), int shooting __attribute__((unused)), int health __attribute__((unused))) {
    return ((((dist_enemy < 50000) ? (1000 - (dist_enemy / 50)) : 0) + (((speed / 20) < 300) ? (speed / 20) : 300)) + (((since_kill_ms < 4000) ? ((600 * (4000 - since_kill_ms)) / 4000) : 0) + (((shooting > 0) ? 250 : 0) + ((150 * (100 - ((health < 0) ? 0 : ((health > 100) ? 100 : health)))) / 100))));
}

int cam_should_cut(int current __attribute__((unused)), int candidate __attribute__((unused)), int ms_on_shot __attribute__((unused)), int min_hold_ms __attribute__((unused)), int hysteresis_permille __attribute__((unused))) {
    if ((ms_on_shot < ((candidate >= (current * 2)) ? (min_hold_ms / 3) : min_hold_ms))) {
    return 0;
    } else {
    if (((candidate * 1000) > (current * (1000 + hysteresis_permille)))) {
    return 1;
    } else {
    return 0;
    }
    }
}

int cam_tri(int t_ms __attribute__((unused)), int period_ms __attribute__((unused))) {
    if (((t_ms % period_ms) < (period_ms / 2))) {
    return (((4000 * (t_ms % period_ms)) / period_ms) - 1000);
    } else {
    return (3000 - ((4000 * (t_ms % period_ms)) / period_ms));
    }
}

int cam_shake_milli(int t_ms __attribute__((unused)), int intensity_permille __attribute__((unused))) {
    return ((intensity_permille * ((2 * cam_tri(t_ms, 130)) + cam_tri((t_ms + 31), 77))) / 3000);
}

int cam_orbit_angle_milli(int t_ms __attribute__((unused)), int period_ms __attribute__((unused))) {
    return ((((t_ms % period_ms) * 3600) / period_ms) * 100);
}

int cam_fov_milli(int dist __attribute__((unused))) {
    if ((dist < 15000)) {
    return 70000;
    } else {
    if ((dist > 80000)) {
    return 40000;
    } else {
    return (70000 - ((30000 * (dist - 15000)) / 65000));
    }
    }
}

